#!/usr/bin/env python3
"""Round 5 — TOC, CN, DBMS, CD, extra coverage. Run: python tools/expand_r5.py data.js"""
import json, re, sys
from pathlib import Path

DEFAULT_DATA_JS = Path(__file__).resolve().parents[2] / "public" / "data" / "data.js"

TOC_R5 = [
  {"id":"cfg_ambiguity","name":"Ambiguous CFGs","topic":"Formal Languages","definition":"CFG is ambiguous if some string has ≥2 distinct parse trees (different derivations).","intuition":"Grammar has a bend in grammar rules letting the same string be parsed multiple ways.","formula":"No algorithm to check if a CFG is ambiguous — undecidable in general.","difficulty":"hard","importance":7,"exam_trick":"Inherently ambiguous CFL: no unambiguous grammar exists for it (e.g., aⁿbⁿcˢ ∪ aˢbⁿcⁿ).","common_mistake":"Ambiguous grammar ≠ ambiguous language. An ambiguous grammar may describe an unambiguous language.","pyq_insight":"GATE: show given string has two parse trees → grammar is ambiguous.","relations":[{"to":"cfl","type":"part_of"}]},
  {"id":"dfa_minimization","name":"DFA Minimization","topic":"Finite Automata","definition":"Find smallest equivalent DFA using table-filling (Myhill-Nerode) algorithm.","intuition":"Merge states you cannot distinguish — equivalent states process all strings identically.","formula":"Mark pairs (q,r) where one is final and one not. Propagate marks. Unmark pairs → equivalent.","difficulty":"hard","importance":9,"exam_trick":"Minimized DFA is unique up to state labeling. Dead/trap state must be explicit in complete DFA.","common_mistake":"States reachable from start state only. First remove unreachable states, then minimize.","pyq_insight":"GATE: minimize given DFA; count states in minimum DFA; verify equivalence of two DFAs.","relations":[{"to":"dfa_nfa","type":"part_of"}]},
  {"id":"myhill_nerode","name":"Myhill-Nerode Theorem","topic":"Formal Languages","definition":"L is regular iff the number of equivalence classes of ≡_L is finite.","intuition":"Group strings by how they affect future acceptance — if finitely many groups, L is regular.","formula":"x ≡_L y iff ∀z: xz∈L ↔ yz∈L. #classes = #states in minimal DFA.","difficulty":"hard","importance":8,"exam_trick":"Myhill-Nerode classes directly correspond to DFA states in minimal DFA.","common_mistake":"Myhill-Nerode is both a test for regularity AND a construction of minimal DFA.","pyq_insight":"GATE: find Myhill-Nerode classes for given language; determine if regular.","relations":[{"to":"dfa_minimization","type":"depends_on"}]},
  {"id":"csl","name":"Context-Sensitive Languages","topic":"Formal Languages","definition":"Languages recognized by Linear Bounded Automata (LBA). aⁿbⁿcⁿ is a classic CSL.","intuition":"More powerful than CFL — can count two things simultaneously.","formula":"LBA = TM restricted to input tape length. CSL ⊂ recursive ⊂ RE.","difficulty":"hard","importance":6,"exam_trick":"CSL: closed under union, intersection, complement, concatenation. Unlike CFL, CSL at complement.","common_mistake":"CFL is NOT closed under complement or intersection of two CFLs — CSL IS.","pyq_insight":"GATE: identify language class; know closure properties of Chomsky hierarchy.","relations":[{"to":"turing_machines","type":"depends_on"}]},
  {"id":"chomsky_hierarchy","name":"Chomsky Hierarchy","topic":"Formal Languages","definition":"Four language classes: Regular (Type 3) ⊂ CFL (Type 2) ⊂ CSL (Type 1) ⊂ RE (Type 0).","intuition":"Like nesting dolls — each inner class has strictly less power than the outer one.","formula":"Type 3: DFA/NFA. Type 2: PDA. Type 1: LBA. Type 0: TM.","difficulty":"medium","importance":9,"exam_trick":"Grammar type = weakest grammar that generates it. Check restrictions systematically.","common_mistake":"A regular language IS also a CFL (accepted by PDA with unused stack).","pyq_insight":"GATE: classify given language in Chomsky hierarchy — very high frequency.","relations":[]},
]

CN_R5 = [
  {"id":"tcp_handshake","name":"TCP 3-Way Handshake","topic":"Transport Layer","definition":"Connection setup: SYN → SYN-ACK → ACK. Teardown: FIN → FIN-ACK → FIN → ACK (4-way).","intuition":"Establishing trust before data transfer: 'I want to talk' → 'Ok, I'm ready' → 'Let's go'.","formula":"Setup: 1.5 RTT delay. Teardown: 2 RTT (FIN can be delayed). TIME_WAIT = 2×MSL.","difficulty":"medium","importance":8,"exam_trick":"SYN flood attack: half-open connections exhaust server resources. SYN cookies mitigate this.","common_mistake":"4-way teardown: server's FIN is separate from server's ACK of client's FIN (FIN-WAIT-2 state).","pyq_insight":"GATE: compute connection setup time; identify TCP state diagram transitions.","relations":[{"to":"tcp_flow","type":"part_of"}]},
  {"id":"udp","name":"UDP — User Datagram Protocol","topic":"Transport Layer","definition":"Connectionless, unreliable, unordered transport protocol. Low overhead.","intuition":"Just throw the packet — no delivery guarantee, no order. Fast and simple.","formula":"UDP header: 8 bytes (src port, dst port, length, checksum). No SYN, no ACK.","difficulty":"easy","importance":7,"exam_trick":"DNS, DHCP, SNMP, TFTP use UDP. Streaming video/games also prefer UDP for low latency.","common_mistake":"UDP DOES have a checksum field (optional in IPv4, mandatory in IPv6).","pyq_insight":"GATE: compare TCP vs UDP; identify appropriate protocol for given application.","relations":[{"to":"osi_model","type":"part_of"}]},
  {"id":"error_detection","name":"Error Detection & Correction","topic":"Data Link Layer","definition":"CRC for error detection. Hamming codes for error correction. Parity for simple detection.","intuition":"Add redundant bits — receiver checks them to detect or even fix bit errors.","formula":"CRC: treat bits as polynomial, divide by generator. Remainder = CRC bits. Detect burst errors.","difficulty":"hard","importance":8,"exam_trick":"Hamming distance d: detect d-1 errors, correct ⌊(d-1)/2⌋ errors.","common_mistake":"CRC DETECTS but doesn't correct errors. Hamming codes can CORRECT single-bit errors.","pyq_insight":"GATE: compute CRC remainder for given data and generator; find Hamming code for data word.","relations":[]},
  {"id":"cdma","name":"CDMA — Code Division Multiple Access","topic":"MAC Protocols","definition":"All stations transmit simultaneously using unique orthogonal codes. Spread spectrum.","intuition":"Everyone speaks simultaneously in different languages — each receiver understands only their language.","formula":"Chip code orthogonality: cᵢ · cⱼ = 0 if i≠j. Inner product of transmitted signal with chip code extracts data.","difficulty":"hard","importance":6,"exam_trick":"CDMA: chip sequences must be orthogonal. Extraction by dot product with known chip code.","common_mistake":"CDMA doesn't prevent interference — orthogonal codes mathematically cancel others out.","pyq_insight":"GATE: compute received signal; decode using chip sequence dot product.","relations":[{"to":"aloha","type":"contrasts_with"}]},
  {"id":"network_layer_routing","name":"OSPF & BGP","topic":"Network Layer","definition":"OSPF: intra-AS link-state routing. BGP: inter-AS path-vector routing.","intuition":"OSPF: within a company's network. BGP: between companies on the internet.","formula":"OSPF uses Dijkstra. BGP selects routes based on policy, not just shortest path.","difficulty":"hard","importance":7,"exam_trick":"OSPF: fast convergence, hierarchical (areas). BGP: policy-based, slow convergence.","common_mistake":"BGP IS NOT shortest-path routing — ISPs choose routes based on business agreements.","pyq_insight":"GATE: identify routing protocol by characteristics; compare convergence properties.","relations":[{"to":"routing","type":"part_of"}]},
  {"id":"congestion_control","name":"Congestion Control vs Flow Control","topic":"Transport Layer","definition":"Flow control: protects receiver (receiver buffer). Congestion control: protects network (router buffer).","intuition":"Flow: 'don't overwhelm ME'. Congestion: 'don't overwhelm the NETWORK between us'.","formula":"TCP window = min(cwnd, rwnd). rwnd: receiver's window (flow). cwnd: congestion window.","difficulty":"medium","importance":8,"exam_trick":"Receiver advertises rwnd. Sender maintains cwnd via slow-start/AIMD. Effective = min(both).","common_mistake":"Flow control ≠ congestion control. Both limit sender rate but for different reasons.","pyq_insight":"GATE: compute effective sending rate given rwnd and cwnd; trace cwnd evolution.","relations":[{"to":"tcp_flow","type":"part_of"}]},
  {"id":"spanning_tree_protocol","name":"Spanning Tree Protocol (STP)","topic":"Data Link Layer","definition":"Prevents bridge loops in Ethernet by disabling redundant links to form a spanning tree.","intuition":"Multiple physical paths between switches cause broadcast storms — STP disables extras.","formula":"Root bridge elected (lowest bridge ID). All ports: root port, designated port, or blocked.","difficulty":"medium","importance":6,"exam_trick":"STP convergence is slow (~50s). RSTP (802.1w) converges in ~1s.","common_mistake":"STP operates at Layer 2 (frames). IP routing handles loops at Layer 3 (TTL).","pyq_insight":"GATE: identify STP port states; determine which links are blocked in given topology.","relations":[]},
]

DBMS_R5 = [
  {"id":"sql_joins","name":"SQL Join Types","topic":"SQL","definition":"INNER: matching rows. LEFT OUTER: all left + matches. FULL OUTER: all from both.","intuition":"INNER = intersection. OUTER = at least one side with NULLs for non-matches.","formula":"INNER JOIN = equi-join where both rows match. CROSS JOIN = Cartesian product.","difficulty":"medium","importance":8,"exam_trick":"Natural join automates equi-join on same-name columns. May drop columns.","common_mistake":"LEFT JOIN and RIGHT JOIN are NOT symmetric. LEFT keeps all LEFT rows regardless.","pyq_insight":"GATE: compute output table for given join type and instance; count rows.","relations":[{"to":"relational_algebra","type":"part_of"}]},
  {"id":"sql_aggregation","name":"SQL Aggregation & GROUP BY","topic":"SQL","definition":"GROUP BY partitions rows into groups; aggregate functions compute per-group statistics.","intuition":"GROUP BY is 'organize by'; aggregate is 'summarize each pile'.","formula":"COUNT(*), SUM, AVG, MIN, MAX. HAVING filters AFTER grouping (WHERE filters before).","difficulty":"medium","importance":8,"exam_trick":"HAVING vs WHERE: WHERE filters rows before grouping; HAVING filters groups after.","common_mistake":"Cannot use non-grouped, non-aggregated columns in SELECT with GROUP BY.","pyq_insight":"GATE: trace GROUP BY output; identify HAVING conditions; correct SQL query.","relations":[]},
  {"id":"subquery","name":"Subqueries & Nested SQL","topic":"SQL","definition":"Query embedded inside another SQL statement. Correlated subquery: references outer query.","intuition":"Subquery = inner query runs first, provides input to outer query.","formula":"EXISTS: returns true if subquery has any row. NOT EXISTS: for 'division' queries.","difficulty":"hard","importance":7,"exam_trick":"NOT EXISTS implements relational division — 'find X such that for ALL Y, condition holds'.","common_mistake":"Correlated subquery is re-evaluated for EACH row of outer query — potentially slow.","pyq_insight":"GATE: write SQL for 'students who took ALL courses' using NOT EXISTS.","relations":[]},
  {"id":"acid_isolation","name":"ACID Isolation Levels","topic":"Transaction Management","definition":"Isolation levels: Read Uncommitted < Read Committed < Repeatable Read < Serializable.","intuition":"Trade-off: higher isolation = fewer anomalies but lower concurrency.","formula":"Anomalies: Dirty Read, Non-repeatable Read, Phantom Read. Serializable prevents all.","difficulty":"hard","importance":8,"exam_trick":"Read Committed prevents dirty reads. Repeatable Read prevents non-repeatable reads too.","common_mistake":"SERIALIZABLE is the strongest isolation — NOT the default in most DBs (Read Committed is usual default).","pyq_insight":"GATE: identify which anomaly is possible at given isolation level.","relations":[{"to":"transactions","type":"part_of"}]},
  {"id":"checkpoint","name":"Checkpointing in Recovery","topic":"Transaction Management","definition":"OS-level snapshot of DB state forcing all dirty pages to disk and logging checkpoint record.","intuition":"Periodic save point — after crash, only need to redo/undo transactions AFTER last checkpoint.","formula":"At crash: UNDO uncommitted transactions. REDO committed-after-checkpoint transactions.","difficulty":"hard","importance":7,"exam_trick":"Active transaction at checkpoint AND committed after checkpoint → REDO it.","common_mistake":"Checkpoint doesn't mean 'all transactions committed'. Active transactions continue past the checkpoint.","pyq_insight":"GATE: given log with checkpoint, identify which transactions to undo and redo.","relations":[{"to":"recovery","type":"part_of"}]},
  {"id":"histogram","name":"Query Cost Estimation","topic":"Query Processing","definition":"Optimizer uses statistics (histograms, row counts) to estimate cost of different plans.","intuition":"Optimizer plays chess — evaluates multiple plans and picks cheapest based on estimated cost.","formula":"Selectivity = fraction of rows satisfying predicate. Estimated output = selectivity × table size.","difficulty":"hard","importance":6,"exam_trick":"Without statistics, optimizer picks WRONG plan. Stale statistics → poor performance.","common_mistake":"Query optimizer doesn't always find OPTIMAL plan — heuristics and limited lookahead.","pyq_insight":"GATE: identify which query plan is cheaper based on given statistics.","relations":[]},
]

CD_R5 = [
  {"id":"liveness","name":"Liveness & Reaching Definitions","topic":"Data Flow Analysis","definition":"Liveness: variable is live if its current value may be used in future. Reaching: which definitions reach each program point.","intuition":"Liveness = 'will this variable be read again?' Reaching = 'which assignment got this variable here?'","formula":"Liveness: backward analysis (use before redefined). Reaching defs: forward analysis.","difficulty":"hard","importance":7,"exam_trick":"Dead code: variable defined but never live after that point → eliminate the assignment.","common_mistake":"Liveness is BACKWARD analysis; Reaching definitions is FORWARD analysis.","pyq_insight":"GATE: compute live variables or reaching definitions at given program point.","relations":[{"to":"optimization","type":"part_of"}]},
  {"id":"register_allocation","name":"Register Allocation & Graph Coloring","topic":"Code Generation","definition":"Map variables to finite physical registers. Model as graph coloring — each variable is a node, interference = edge.","intuition":"Variables that are 'live' simultaneously conflict — must be in different registers.","formula":"Build interference graph. k-coloring with k=registers. If not k-colorable → spill to memory.","difficulty":"hard","importance":7,"exam_trick":"Register allocation is NP-complete in general. Chaitin's algorithm uses graph coloring.","common_mistake":"Spilling adds load/store instructions — should minimize spills for performance.","pyq_insight":"GATE: compute number of registers needed; build interference graph for given program.","relations":[]},
  {"id":"basic_block","name":"Basic Blocks & Control Flow Graph","topic":"Code Generation","definition":"Basic block: maximal straight-line code with no branches in/out. CFG: nodes = blocks, edges = jumps.","intuition":"Slice program into chunks with no jumps inside. Connect them by jump targets.","formula":"Block starts at: function entry, branch target, after branch. Ends at: branch, return.","difficulty":"medium","importance":7,"exam_trick":"Optimizations within a basic block: CSE, constant folding, dead code. Cross-block: data flow analysis.","common_mistake":"Basic block starts at jump TARGET and after jump — both conditions must be checked.","pyq_insight":"GATE: partition code into basic blocks; draw CFG; apply local optimization.","relations":[]},
  {"id":"peephole_opt","name":"Peephole Optimization","topic":"Code Optimization","definition":"Replace short code sequences with faster equivalents using pattern-matching on small window.","intuition":"Scan a sliding window of 2-4 instructions; replace inefficient patterns with better ones.","formula":"Patterns: eliminate redundant loads/stores, strength reduction (x*2 → x<<1), jump-to-jump.","difficulty":"medium","importance":6,"exam_trick":"Jump-to-jump: jmp L1; L1: jmp L2 → jmp L2. Common peephole pattern.","common_mistake":"Peephole is LOCAL — it doesn't use data flow info. Only pattern-based.","pyq_insight":"GATE: identify applicable peephole optimization for given instruction sequence.","relations":[{"to":"optimization","type":"part_of"}]},
]

def build_all():
    return {"toc": TOC_R5, "cn": CN_R5, "dbms": DBMS_R5, "cd": CD_R5}

def merge(new_concepts, data_js_path):
    text = data_js_path.read_text(encoding="utf-8", errors="ignore")
    existing = {}
    m = re.search(r'const CONCEPTS=(\{[\s\S]*?\});\n', text)
    if m:
        try: existing = json.loads(m.group(1))
        except: pass
    merged = dict(existing); added = 0
    for sid, concepts in new_concepts.items():
        if sid not in merged: merged[sid] = []
        seen = {c['id'] for c in merged[sid]}
        new = [c for c in concepts if c['id'] not in seen]
        merged[sid].extend(new); added += len(new)
    payload = json.dumps(merged, ensure_ascii=False, indent=2)
    new_block = f"\n// ═══ CONCEPTS DATA ═══\nconst CONCEPTS={payload};\n"
    text = re.sub(r'\n// ═══ CONCEPTS DATA ═══\nconst CONCEPTS=\{[\s\S]*?\};\n', new_block, text)
    if new_block not in text:
        text = text.replace("// ═══ REVISION CONTENT DATA ═══", new_block + "\n// ═══ REVISION CONTENT DATA ═══", 1)
    data_js_path.write_text(text, encoding="utf-8")
    total = sum(len(v) for v in merged.values())
    print(f"✅ R5 done! Added: {added}  Total: {total}")
    for s in sorted(merged): print(f"   {s:6s}: {len(merged[s])}")

if __name__ == "__main__":
    merge(build_all(), Path(sys.argv[1]) if len(sys.argv)>1 else DEFAULT_DATA_JS)
