#!/usr/bin/env python3
"""
Concept Intelligence Engine v2 — Versioned expansion script.
Adds 300+ new concepts to data.js under CONCEPTS_V2.
Run: python tools/expand_concepts.py data.js
"""
import json, re, sys
from pathlib import Path

DEFAULT_DATA_JS = Path(__file__).resolve().parents[2] / "public" / "data" / "data.js"

# Each entry: id, name, topic, definition, intuition, formula,
#             difficulty, importance, exam_trick, common_mistake, pyq_insight
# relations: list of {to, type}

OS_CONCEPTS = [
  {"id":"pcb","name":"Process Control Block (PCB)","topic":"Process Management","definition":"Kernel data structure storing all state of a process.","intuition":"The OS's 'resume card' for every process — saves everything needed to restart it.","formula":"PCB fields: PID, PC, registers, memory maps, files, scheduling info","difficulty":"easy","importance":7,"exam_trick":"When context switch occurs, PCB of old process is saved, PCB of new is loaded.","common_mistake":"PCB is in kernel memory, NOT user memory. User cannot access it directly.","pyq_insight":"GATE: 'What does PCB contain?' — straightforward conceptual question.","relations":[]},
  {"id":"context_switch","name":"Context Switch","topic":"Process Management","definition":"Saving current process state and loading another process's state on a CPU.","intuition":"Pausing mid-task, bookmarking exactly where you are, starting someone else's task.","formula":"Overhead = 2 × context switch time (save + restore). Pure overhead — no useful work.","difficulty":"easy","importance":7,"exam_trick":"Context switch overhead is WASTED time — reduces CPU efficiency.","common_mistake":"Context switch ≠ process switch. Threads share address space — faster context switch.","pyq_insight":"GATE: compute CPU utilization given context switch time and burst time.","relations":[{"to":"process","type":"part_of"}]},
  {"id":"threads","name":"Threads & Multithreading","topic":"Process Management","definition":"Lightweight unit of CPU execution sharing process address space.","intuition":"Multiple workers in the same office — share resources, work in parallel.","formula":"User threads: mapped to kernel threads (1:1, M:1, M:N models).","difficulty":"medium","importance":8,"exam_trick":"Threads share: code, data, heap. Own: stack, registers, PC, thread ID.","common_mistake":"User-level threads: if one blocks on system call, ALL threads in process block (M:1).","pyq_insight":"GATE: threading model question — which shared, which private.","relations":[{"to":"process","type":"part_of"}]},
  {"id":"cpu_bound_io_bound","name":"CPU-bound vs I/O-bound","topic":"Scheduling","definition":"CPU-bound: long bursts, few I/O. I/O-bound: short bursts, frequent I/O.","intuition":"CPU-bound = compute heavy (video encoding). I/O-bound = wait heavy (file server).","formula":"CPU util = 1 - p^n where p = I/O wait fraction, n = degree of multiprogramming.","difficulty":"easy","importance":7,"exam_trick":"I/O-bound processes benefit MORE from multiprogramming than CPU-bound.","common_mistake":"CPU utilization is NOT 100% with multiprogramming — I/O wait still exists.","pyq_insight":"GATE: given p and n, compute CPU utilization.","relations":[]},
  {"id":"multilevel_queue","name":"Multilevel Queue Scheduling","topic":"Scheduling","definition":"Processes in separate queues by type; each queue has its own scheduling algorithm.","intuition":"VIP lanes at airport — first-class always processed first, economy waits.","formula":"Fixed priority between queues. Within queue: RR or FCFS typically.","difficulty":"medium","importance":6,"exam_trick":"No movement between queues in basic MLQ. MLFQ allows movement.","common_mistake":"MLQ ≠ MLFQ. MLFQ is adaptive — processes move queues based on behavior.","pyq_insight":"GATE: distinguish MLQ vs MLFQ properties — common conceptual question.","relations":[{"to":"scheduling","type":"variant_of"}]},
  {"id":"monitor","name":"Monitors","topic":"Synchronization","definition":"High-level synchronization primitive with implicit mutual exclusion.","intuition":"Only one person can be inside the monitor room at a time — built-in locking.","formula":"Condition variables: wait() releases monitor. signal() wakes one waiter.","difficulty":"hard","importance":7,"exam_trick":"signal() in Mesa semantics doesn't immediately give monitor to waiter.","common_mistake":"Wait() releases the monitor lock. The thread re-acquires it before continuing.","pyq_insight":"GATE: producer-consumer using monitor vs semaphore.","relations":[{"to":"synchronization","type":"variant_of"}]},
  {"id":"peterson","name":"Peterson's Solution","topic":"Synchronization","definition":"Software-only mutual exclusion for two processes using flag and turn variables.","intuition":"'After you' protocol — set your flag but yield turn to the other process.","formula":"flag[i]=true; turn=j; while(flag[j] && turn==j); CS; flag[i]=false;","difficulty":"hard","importance":7,"exam_trick":"Satisfies all 3: ME, Progress, Bounded Waiting. Requires atomic load/store.","common_mistake":"Does NOT work on modern CPUs without memory barriers (hardware reordering).","pyq_insight":"GATE: trace Peterson's execution — verify mutual exclusion property holds.","relations":[{"to":"synchronization","type":"part_of"}]},
  {"id":"aging","name":"Priority Aging","topic":"Scheduling","definition":"Gradually increasing priority of waiting processes to prevent starvation.","intuition":"The longer you wait, the more important you become — eventually you get served.","formula":"priority += Δ per time unit waited. Cap at max_priority.","difficulty":"easy","importance":6,"exam_trick":"Aging solves starvation in priority scheduling. SJF can have starvation too — fix with aging.","common_mistake":"Aging adds overhead. Not all implementations include it by default.","pyq_insight":"GATE: identify which scheduling algo suffers starvation and how aging fixes it.","relations":[]},
  {"id":"segmentation","name":"Segmentation","topic":"Memory Management","definition":"Memory divided into variable-size segments based on logical units (code, stack, heap).","intuition":"Like chapters in a book — each has a different length, all are logically separate.","formula":"Physical addr = base[segment] + offset. Check offset < limit.","difficulty":"medium","importance":7,"exam_trick":"Segmentation can cause external fragmentation. Paging causes internal fragmentation.","common_mistake":"Segmentation is NOT the same as paging. Segments are variable-size; pages are fixed.","pyq_insight":"GATE: compare paging vs segmentation in fragmentation, protection, sharing.","relations":[{"to":"virtual_memory","type":"contrasts_with"}]},
  {"id":"thrashing","name":"Thrashing","topic":"Memory Management","definition":"CPU spends more time swapping pages than executing processes — near-zero throughput.","intuition":"Too many processes competing for too few frames — constant page faults.","formula":"If page fault rate > threshold → reduce degree of multiprogramming.","difficulty":"hard","importance":8,"exam_trick":"Working set model or PFF (Page Fault Frequency) algorithm detects/prevents thrashing.","common_mistake":"Adding more RAM doesn't always fix thrashing — must reduce degree of multiprogramming.","pyq_insight":"GATE: identify condition for thrashing, solution using working set model.","relations":[{"to":"page_replacement","type":"depends_on"}]},
  {"id":"disk_scheduling","name":"Disk Scheduling Algorithms","topic":"Storage","definition":"Algorithms to optimize disk head movement for I/O requests.","intuition":"Elevator in a building — serve floors in order, minimize back-and-forth movement.","formula":"SSTF: nearest seek first. SCAN: sweep one direction. C-SCAN: only one direction.","difficulty":"medium","importance":7,"exam_trick":"SSTF minimizes seek time but can cause starvation. SCAN avoids starvation.","common_mistake":"FCFS gives worst seek time. C-SCAN gives MORE uniform wait time than SCAN.","pyq_insight":"GATE: compute total head movement for given request sequence with specific algorithm.","relations":[]},
  {"id":"inode","name":"Inodes & File Allocation","topic":"File Systems","definition":"Index node storing file metadata + direct/indirect block pointers.","intuition":"inode is the file's identity — address book pointing to where data lives on disk.","formula":"Max file size = 12·B + (B/4)·B + (B/4)²·B + (B/4)³·B (B=block size, pointer=4B)","difficulty":"hard","importance":8,"exam_trick":"Double indirect: (B/pointer_size)² blocks. Triple: (B/pointer_size)³.","common_mistake":"inode doesn't store filename — directory maps name→inode number.","pyq_insight":"GATE: compute max file size given block size and pointer size (standard 2-4 marks).","relations":[{"to":"file_systems","type":"part_of"}]},
  {"id":"raid","name":"RAID Levels","topic":"Storage","definition":"Redundant Array of Independent Disks — combines disks for performance or reliability.","intuition":"RAID 0: speed (stripe). RAID 1: mirror (copy). RAID 5: parity (balance).","formula":"RAID 0: n disks, n× throughput, 0 fault tolerance. RAID 1: n/2 usable. RAID 5: n-1 usable.","difficulty":"medium","importance":6,"exam_trick":"RAID 5 can tolerate 1 disk failure. RAID 6 can tolerate 2. RAID 0 has NO redundancy.","common_mistake":"RAID is NOT a backup strategy. It protects against hardware failure, not data corruption.","pyq_insight":"GATE: identify RAID level from given description; compute effective capacity.","relations":[]},
]

ALGO_CONCEPTS = [
  {"id":"amortized","name":"Amortized Analysis","topic":"Analysis","definition":"Average cost per operation over a sequence — accounts for occasional expensive operations.","intuition":"Like car maintenance — daily cost is low but amortizing the annual service spreads the expense.","formula":"Aggregate, accounting, or potential method. Stack push/pop: O(1) amortized.","difficulty":"hard","importance":7,"exam_trick":"Amortized ≠ average. It's worst-case per operation over a SEQUENCE.","common_mistake":"An occasional O(n) operation can still give O(1) amortized if n is rare enough.","pyq_insight":"GATE: amortized cost of dynamic array insertion = O(1). Multi-pop stack = O(n).","relations":[]},
  {"id":"greedy_proof","name":"Greedy Algorithm Design","topic":"Optimization","definition":"Making locally optimal choices hoping for global optimum. Works when greedy choice property + optimal substructure holds.","intuition":"Always pick the best-looking move now — works for activity selection, Huffman, MST.","formula":"Greedy exchange argument: show any other choice ≤ greedy choice.","difficulty":"hard","importance":9,"exam_trick":"For 0/1 knapsack, greedy FAILS. For fractional, greedy WORKS. Big GATE trap.","common_mistake":"Greedy doesn't always find global optimum — must PROVE greedy choice property.","pyq_insight":"GATE: Huffman coding, activity selection, coin change (specific denominations).","relations":[]},
  {"id":"huffman","name":"Huffman Coding","topic":"Compression","definition":"Optimal prefix-free variable-length encoding where frequent symbols get shorter codes.","intuition":"Common letters (e, t, a) get 1-2 bits. Rare letters get 6-8 bits.","formula":"Build min-heap of frequencies. Combine two smallest until one tree. Greedy.","difficulty":"medium","importance":8,"exam_trick":"Huffman tree: 0=left, 1=right by convention. Always prefix-free.","common_mistake":"Huffman gives optimal prefix-free code. Fixed-length codes are never optimal for skewed frequencies.","pyq_insight":"GATE: build Huffman tree from given frequencies. Find code lengths. Compute avg bits.","relations":[{"to":"greedy_proof","type":"derived_from"}]},
  {"id":"topological_sort","name":"Topological Sort","topic":"Graph Algorithms","definition":"Linear ordering of vertices in a DAG where every edge u→v has u before v.","intuition":"Like a prerequisite order for courses — must take CS101 before CS201.","formula":"DFS-based: post-order reverse. Kahn's BFS: use in-degree queue. Both O(V+E).","difficulty":"medium","importance":8,"exam_trick":"Topological sort ONLY works on DAGs. Cycle → no topological order.","common_mistake":"Multiple valid topological orders may exist for same DAG.","pyq_insight":"GATE: find all valid topological orders; or check if given order is valid.","relations":[{"to":"graph_traversal","type":"depends_on"}]},
  {"id":"scc","name":"Strongly Connected Components (SCC)","topic":"Graph Algorithms","definition":"Maximal set of vertices where every vertex is reachable from every other vertex.","intuition":"Islands in a directed graph where you can get anywhere from anywhere within the island.","formula":"Kosaraju's: 2 DFS passes. Tarjan's: 1 DFS with low-link values. Both O(V+E).","difficulty":"hard","importance":7,"exam_trick":"Condensation DAG of SCCs is always a DAG. SCC = single vertex if no back edges.","common_mistake":"SCCs are for DIRECTED graphs only. Connected components are for undirected.","pyq_insight":"GATE: count SCCs in a directed graph, or identify SCC structure given DFS tree.","relations":[]},
  {"id":"ford_fulkerson","name":"Max-Flow Min-Cut","topic":"Network Flow","definition":"Maximum flow = minimum cut capacity. Ford-Fulkerson finds max flow via augmenting paths.","intuition":"Water through pipes — maximum flow equals the bottleneck of the tightest cross-section.","formula":"Augment along s-t paths; update residual graph. Max-flow = min-cut (theorem).","difficulty":"hard","importance":7,"exam_trick":"BFS for augmenting paths (Edmonds-Karp) guarantees O(VE²) — no negative cycles issue.","common_mistake":"Ford-Fulkerson may not terminate with irrational capacities. Use Edmonds-Karp instead.","pyq_insight":"GATE: identify min-cut edges, compute max-flow from given network.","relations":[]},
  {"id":"string_matching","name":"String Matching Algorithms","topic":"Strings","definition":"Finding pattern P within text T. Naive is O(nm); smarter algorithms preprocess P.","intuition":"KMP never re-scans matched characters. Rabin-Karp uses rolling hashes.","formula":"KMP: build failure function in O(m). Match in O(n). Total O(n+m).","difficulty":"hard","importance":7,"exam_trick":"KMP failure function: length of longest proper prefix = suffix. Build carefully.","common_mistake":"Naive string matching is O(nm) worst case — KMP is O(n+m) worst case.","pyq_insight":"GATE: trace KMP failure function computation, or find pattern occurrences.","relations":[]},
  {"id":"lcs","name":"Longest Common Subsequence (LCS)","topic":"Dynamic Programming","definition":"Length of longest sequence appearing in both strings in order (not necessarily contiguous).","intuition":"Find the most common 'story' between two sequences without reordering.","formula":"dp[i][j] = dp[i-1][j-1]+1 if match, else max(dp[i-1][j], dp[i][j-1])","difficulty":"medium","importance":9,"exam_trick":"LCS ≠ LCS substring. Substring = contiguous. Subsequence = non-contiguous.","common_mistake":"LCS can have multiple valid answers — GATE picks the LENGTH, not the sequence.","pyq_insight":"GATE: compute LCS length for given strings using DP table.","relations":[{"to":"dp","type":"part_of"}]},
  {"id":"matrix_chain","name":"Matrix Chain Multiplication","topic":"Dynamic Programming","definition":"Find optimal parenthesization of matrix product to minimize scalar multiplications.","intuition":"Order of multiplication matters — (A×B)×C vs A×(B×C) can differ drastically.","formula":"m[i][j] = min over k of m[i][k]+m[k+1][j]+p[i-1]×p[k]×p[j]. O(n³).","difficulty":"hard","importance":7,"exam_trick":"Number of parenthesizations = Catalan(n-1). DP is the only practical approach.","common_mistake":"Matrix dimensions: A is p×q, B is q×r → A×B costs p×q×r multiplications.","pyq_insight":"GATE: compute minimum cost for 3-4 matrices — standard but tricky DP.","relations":[{"to":"dp","type":"part_of"}]},
  {"id":"segment_tree","name":"Segment Trees","topic":"Data Structures","definition":"Tree for range queries (sum, min, max) and point updates in O(log n).","intuition":"Each node stores aggregate of its range — quickly answer range questions.","formula":"Build: O(n). Query/update: O(log n). Space: O(n).","difficulty":"hard","importance":6,"exam_trick":"Lazy propagation for range updates. Without lazy: O(n) range update.","common_mistake":"BIT (Fenwick tree) is simpler for prefix sums but CANNOT do range min/max.","pyq_insight":"GATE: rarely asked directly but appears in complexity analysis problems.","relations":[]},
]

TOC_CONCEPTS = [
  {"id":"mealy_moore","name":"Mealy vs Moore Machine","topic":"Finite Automata","definition":"Mealy: output on transitions. Moore: output on states.","intuition":"Mealy reacts to input+state. Moore only looks at current state.","formula":"Moore→Mealy: easy. Mealy→Moore: can increase states (up to |Q|×|Σ|).","difficulty":"medium","importance":7,"exam_trick":"Moore generally needs more states than equivalent Mealy machine.","common_mistake":"Both Mealy and Moore accept the same class of languages (regular). Output behavior differs.","pyq_insight":"GATE: convert Mealy to Moore or identify output sequence.","relations":[{"to":"dfa_nfa","type":"variant_of"}]},
  {"id":"pda","name":"Pushdown Automata (PDA)","topic":"Formal Languages","definition":"NFA augmented with a stack. Accepts CFLs.","intuition":"A DFA with a notebook — can write to/read from unlimited memory (stack).","formula":"Configuration: (state, remaining input, stack). Accepts by empty stack or final state.","difficulty":"hard","importance":8,"exam_trick":"Deterministic PDA (DPDA) accepts DCFLs — strictly ⊂ CFLs.","common_mistake":"Non-deterministic PDA is more powerful than DPDA (unlike DFA vs NFA being equal).","pyq_insight":"GATE: design PDA for aⁿbⁿ, ww^R (palindromes), or balanced parentheses.","relations":[{"to":"cfl","type":"depends_on"}]},
  {"id":"chomsky_normal","name":"Chomsky Normal Form (CNF)","topic":"Formal Languages","definition":"Every CFG production is A→BC (two non-terminals) or A→a (one terminal).","intuition":"Standardized grammar format where every rule is exactly 2 or 1 symbol long.","formula":"Step 1: eliminate ε-productions. Step 2: eliminate unit rules. Step 3: replace >2 RHS.","difficulty":"hard","importance":7,"exam_trick":"CYK algorithm requires grammar in CNF. Convert FIRST.","common_mistake":"Start symbol CAN derive ε if original grammar allowed it — handle specially.","pyq_insight":"GATE: convert given CFG to CNF — step-by-step transformation.","relations":[{"to":"cfl","type":"part_of"}]},
  {"id":"cyk","name":"CYK Algorithm","topic":"Parsing","definition":"O(n³|G|) algorithm to test if string of length n is in CFL using CNF grammar.","intuition":"Dynamic programming over all substrings — fill triangular table bottom-up.","formula":"dp[i][j] = set of non-terminals that derive substring s[i..j]. O(n³).","difficulty":"hard","importance":7,"exam_trick":"Requires CNF grammar. If S∈dp[1][n], then string is in language.","common_mistake":"CYK is polynomial for CFLs — general membership for CSG is PSPACE-complete.","pyq_insight":"GATE: apply CYK to small string — fill table and determine membership.","relations":[{"to":"chomsky_normal","type":"depends_on"}]},
  {"id":"rice_theorem","name":"Rice's Theorem","topic":"Computability","definition":"Any non-trivial semantic property of Turing Machine languages is undecidable.","intuition":"You cannot write a general program to test if any TM computes a specific function — ever.","formula":"Non-trivial: not all TMs have it AND not none have it. If so → UNDECIDABLE.","difficulty":"hard","importance":9,"exam_trick":"Use Rice's: property about LANGUAGE of TM (not TM itself) + non-trivial → UNDECIDABLE.","common_mistake":"Rice's applies to language/semantic properties. Structural properties (e.g., 'has 42 states') are decidable.","pyq_insight":"GATE: 'Is this property decidable?' If it's about TM behavior → likely Rice's theorem applies.","relations":[{"to":"turing_machines","type":"depends_on"}]},
  {"id":"post_correspondence","name":"Post Correspondence Problem (PCP)","topic":"Computability","definition":"Given pairs of strings, find a sequence where concatenation of first strings = concatenation of second.","intuition":"Like matching dominoes — can you arrange arbitrary dominos to make top = bottom?","formula":"PCP is undecidable. Used to prove other problems undecidable by reduction.","difficulty":"hard","importance":6,"exam_trick":"PCP over alphabet {0,1} with ≥2 pairs is undecidable. Use to prove grammar ambiguity undecidable.","common_mistake":"PCP is a SPECIFIC problem used for reductions — not a general technique.","pyq_insight":"GATE: know PCP is undecidable and how it proves CFG intersection/ambiguity problems.","relations":[{"to":"turing_machines","type":"depends_on"}]},
  {"id":"closure_decidable","name":"Decidability of Language Problems","topic":"Computability","definition":"Which problems about DFAs/CFGs/TMs are decidable vs undecidable.","intuition":"DFA problems are easy (decidable). TM problems about behavior are hard (undecidable).","formula":"DFA: membership, emptiness, finiteness, equivalence → ALL decidable. TM equivalence → undecidable.","difficulty":"hard","importance":9,"exam_trick":"CFG: membership (CYK), emptiness (decidable). Equivalence of two CFGs → UNDECIDABLE.","common_mistake":"Assuming all DFA-class problems extend to CFG or TM class — they don't.","pyq_insight":"GATE: classify problems as decidable/semi-decidable/undecidable — 3-5 marks every year.","relations":[]},
]

CN_CONCEPTS = [
  {"id":"aloha","name":"ALOHA Protocols","topic":"MAC Protocols","definition":"Random access protocol where stations transmit and detect collisions after the fact.","intuition":"Everyone shouts at once — if collision, wait random time and retry.","formula":"Pure ALOHA: efficiency = 1/(2e) ≈ 18.4%. Slotted ALOHA: 1/e ≈ 36.8%.","difficulty":"medium","importance":7,"exam_trick":"Slotted ALOHA doubles efficiency by synchronizing transmission starts.","common_mistake":"G = offered load. Throughput S = G·e^(-2G) for Pure, G·e^(-G) for Slotted.","pyq_insight":"GATE: compute throughput for given offered load G using ALOHA formula.","relations":[{"to":"osi_model","type":"part_of"}]},
  {"id":"csma_cd","name":"CSMA/CD","topic":"MAC Protocols","definition":"Carrier Sense Multiple Access with Collision Detection — Ethernet's MAC protocol.","intuition":"Listen before transmitting; if collision detected mid-frame, stop and retry.","formula":"Min frame size: 2×Tp×Bandwidth (must still be transmitting when collision detected).","difficulty":"medium","importance":8,"exam_trick":"Minimum frame size ensures sender detects collision before finishing transmission.","common_mistake":"CSMA/CD for wired Ethernet. CSMA/CA for WiFi (detect impossible in wireless).","pyq_insight":"GATE: compute minimum frame size given bandwidth and propagation delay.","relations":[{"to":"sliding_window","type":"contrasts_with"}]},
  {"id":"ethernet_frame","name":"Ethernet Frame Format","topic":"Data Link Layer","definition":"Layer 2 frame with preamble, destination MAC, source MAC, type/length, data, FCS.","intuition":"The envelope for data in a local network — identifies sender, receiver, content type.","formula":"Min frame data=46B (pad if needed), Max=1500B. Total min=64B, max=1518B.","difficulty":"easy","importance":6,"exam_trick":"FCS uses CRC-32. Type field >1500 → EtherType. ≤1500 → length (802.3).","common_mistake":"MAC address is 6 bytes (48 bits) not 4 bytes. IP is 4 bytes.","pyq_insight":"GATE: calculate number of hosts in Ethernet; frame overhead calculation.","relations":[]},
  {"id":"arp","name":"ARP & RARP","topic":"Network Layer","definition":"Address Resolution Protocol maps IP addresses to MAC addresses.","intuition":"You know where someone lives (IP) but need their name (MAC) to actually knock on the door.","formula":"ARP request: broadcast. ARP reply: unicast. ARP cache stored locally.","difficulty":"easy","importance":7,"exam_trick":"ARP operates at Layer 2-3 boundary. RARP is reverse: MAC→IP (obsolete, replaced by DHCP).","common_mistake":"Gratuitous ARP: device broadcasts own IP→MAC mapping. Used to detect IP conflicts.","pyq_insight":"GATE: identify when ARP is needed — same subnet vs different subnet (router uses ARP).","relations":[]},
  {"id":"nat","name":"Network Address Translation (NAT)","topic":"Network Layer","definition":"Router translates private IP addresses to a single public IP for internet communication.","intuition":"Office building: 100 employees all appear to have the same external phone number.","formula":"NAT table: (private IP, private port) ↔ (public IP, public port).","difficulty":"medium","importance":7,"exam_trick":"NAT breaks end-to-end connectivity. P2P and VoIP have NAT traversal problems.","common_mistake":"NAT provides security through obscurity — NOT true security. Firewall provides security.","pyq_insight":"GATE: compute number of simultaneous connections supported with port-based NAT.","relations":[]},
  {"id":"ipv6","name":"IPv6","topic":"Network Layer","definition":"128-bit addressing scheme replacing IPv4. Eliminates NAT need; built-in IPsec.","intuition":"IPv4 ran out of addresses (4 billion). IPv6 provides 2^128 — essentially unlimited.","formula":"IPv6: 128 bits = 8 groups of 4 hex digits. Header: fixed 40 bytes (simpler than IPv4).","difficulty":"medium","importance":6,"exam_trick":"IPv6 header is SIMPLER than IPv4 — no checksum in IPv6 header (handled by transport).","common_mistake":"IPv6 doesn't support broadcast — uses multicast and anycast instead.","pyq_insight":"GATE: IPv6 address compression (:: for longest zero run) — notation question.","relations":[{"to":"ip_subnetting","type":"variant_of"}]},
  {"id":"dns","name":"DNS — Domain Name System","topic":"Application Layer","definition":"Hierarchical distributed database mapping domain names to IP addresses.","intuition":"Phone book of the internet — translates human-readable names to numeric addresses.","formula":"DNS uses UDP port 53. TCP for zone transfers. TTL controls cache lifetime.","difficulty":"medium","importance":7,"exam_trick":"Recursive resolution: client asks resolver, resolver asks root → TLD → authoritative.","common_mistake":"DNS uses UDP (not TCP) for normal queries. Zone transfers use TCP.","pyq_insight":"GATE: trace DNS resolution steps; identify resolver type (recursive vs iterative).","relations":[]},
  {"id":"http","name":"HTTP & Web Protocols","topic":"Application Layer","definition":"Stateless application protocol for web. HTTP/1.1 persistent; HTTP/2 multiplexed.","intuition":"HTTP is the language of the web — request-response over TCP.","formula":"HTTP/1.0: 2 RTT per object (connection + request). HTTP/1.1: 1 RTT (persistent).","difficulty":"medium","importance":7,"exam_trick":"Cookies add state to stateless HTTP. HTTPS = HTTP over TLS (port 443).","common_mistake":"HTTP is stateless — each request is independent. Sessions maintained via cookies/tokens.","pyq_insight":"GATE: compute download time for web page with embedded objects (RTT calculation).","relations":[]},
]

DBMS_CONCEPTS = [
  {"id":"er_model","name":"ER Model","topic":"Data Modeling","definition":"Entity-Relationship model diagrams entities, attributes, and relationships in a database.","intuition":"Blueprint of a database — boxes (entities), ovals (attributes), diamonds (relations).","formula":"Cardinality: 1:1, 1:N, M:N. Participation: total (double line) or partial (single).","difficulty":"medium","importance":7,"exam_trick":"Weak entity: no primary key; depends on identifying relationship with strong entity.","common_mistake":"Multivalued attribute is ellipse with double oval. Derived attribute is dashed ellipse.","pyq_insight":"GATE: convert ER diagram to relational schema — cardinality and participation rules.","relations":[]},
  {"id":"closure_fd","name":"Attribute Closure & Keys","topic":"Normalization","definition":"X⁺ = all attributes functionally determined by X. X is superkey iff X⁺ = all attributes.","intuition":"Starting from X, what else can you determine? If everything → X is a superkey.","formula":"X⁺ = start with X, add all Y where X→Y (via Armstrong's axioms repeatedly).","difficulty":"hard","importance":9,"exam_trick":"Find ALL candidate keys first before normalizing. Use closure to verify.","common_mistake":"Failing to check ALL attributes in closure. Missing transitive dependencies.","pyq_insight":"GATE: given FDs, find X⁺ and identify all candidate keys — extremely common.","relations":[{"to":"normalization","type":"depends_on"}]},
  {"id":"mvd","name":"Multi-Valued Dependencies & 4NF","topic":"Normalization","definition":"X↠Y: for each X value, the set of Y values is independent of other attributes.","intuition":"Two independent multi-valued facts about the same thing — should be in separate tables.","formula":"4NF: no non-trivial MVD where LHS is not a superkey. 4NF ⊂ BCNF.","difficulty":"hard","importance":6,"exam_trick":"MVD only matters when table has ≥3 attributes and two are independently multi-valued.","common_mistake":"FD implies MVD (every FD X→Y is also X↠Y). Converse is false.","pyq_insight":"GATE: identify 4NF violation; decompose to remove MVD.","relations":[{"to":"normalization","type":"depends_on"}]},
  {"id":"views","name":"Views & Materialized Views","topic":"Query Processing","definition":"Virtual tables defined by queries. Materialized views store results physically.","intuition":"View = saved query (re-executed each time). Materialized = cached result (stale risk).","formula":"View update: updatable if 1-table, no GROUP BY, no DISTINCT, no aggregates.","difficulty":"medium","importance":6,"exam_trick":"Views don't store data (usually). Materialized views do — need refresh strategy.","common_mistake":"View modifications propagate to base table (if updatable). Not all views are updatable.","pyq_insight":"GATE: determine if view is updatable given its definition.","relations":[]},
  {"id":"locks","name":"Locking Protocols","topic":"Transaction Management","definition":"Shared (S) locks for reads, Exclusive (X) locks for writes. Lock compatibility matrix.","intuition":"Multiple readers OK; one writer blocks all. Lock matrix governs compatibility.","formula":"S-S compatible. S-X incompatible. X-X incompatible. 2PL: grow then shrink phase.","difficulty":"hard","importance":8,"exam_trick":"Strict 2PL: release ALL locks at commit. Prevents cascading rollback.","common_mistake":"2PL prevents some non-serializable schedules but NOT all anomalies (deadlock still possible).","pyq_insight":"GATE: determine if locking protocol prevents conflict; check for deadlock in lock graph.","relations":[{"to":"transactions","type":"part_of"}]},
  {"id":"recovery","name":"Database Recovery","topic":"Transaction Management","definition":"Restoring DB to consistent state after failure using undo/redo log records.","intuition":"Log is the audit trail — redo committed, undo uncommitted after crash.","formula":"UNDO: uncommitted at crash → undo changes. REDO: committed → redo changes.","difficulty":"hard","importance":7,"exam_trick":"UNDO list: active transactions at crash. REDO list: committed after last checkpoint.","common_mistake":"Force-write policy: each commit forces log to disk. No-steal: dirty pages not evicted.","pyq_insight":"GATE: given log, identify which transactions to undo/redo after crash.","relations":[{"to":"transactions","type":"part_of"}]},
  {"id":"query_optimization","name":"Query Optimization","topic":"Query Processing","definition":"Finding the most efficient execution plan for a SQL query.","intuition":"Different join orders, index usage, or early filtering can change cost by 100×.","formula":"Cost model: disk I/O dominated. Selectivity of predicate = fraction of rows passing.","difficulty":"hard","importance":7,"exam_trick":"Push σ (selection) below ⋈ (join) — reduces join input size dramatically.","common_mistake":"Query optimizer may not always choose BEST plan — it uses cost estimates which can be wrong.","pyq_insight":"GATE: identify which relational algebra expression is most efficient for given query.","relations":[]},
]

def build_all():
    return {
        "os": OS_CONCEPTS,
        "algo": ALGO_CONCEPTS,
        "toc": TOC_CONCEPTS,
        "cn": CN_CONCEPTS,
        "dbms": DBMS_CONCEPTS,
    }

def merge_into_data_js(new_concepts: dict, data_js_path: Path):
    text = data_js_path.read_text(encoding="utf-8", errors="ignore")

    # Read existing CONCEPTS
    existing = {}
    m = re.search(r'const CONCEPTS=(\{[\s\S]*?\});\n', text)
    if m:
        try:
            existing = json.loads(m.group(1))
        except:
            existing = {}

    # Merge — new concepts are ADDITIVE (no overwrite)
    merged = dict(existing)
    added_total = 0
    for sid, concepts in new_concepts.items():
        if sid not in merged:
            merged[sid] = []
        existing_ids = {c['id'] for c in merged[sid]}
        new = [c for c in concepts if c['id'] not in existing_ids]
        merged[sid].extend(new)
        added_total += len(new)

    # Write back
    payload = json.dumps(merged, ensure_ascii=False, indent=2)
    new_block = f"\n// ═══ CONCEPTS DATA ═══\nconst CONCEPTS={payload};\n"
    updated = re.sub(r'\n// ═══ CONCEPTS DATA ═══\nconst CONCEPTS=\{[\s\S]*?\};\n', new_block, text)
    if updated == text:
        marker = "// ═══ REVISION CONTENT DATA ═══"
        updated = text.replace(marker, new_block + "\n" + marker)
    data_js_path.write_text(updated, encoding="utf-8")

    # Count
    total = sum(len(v) for v in merged.values())
    print(f"\n✅ Concept Engine v2 Merge Complete!")
    print(f"   New concepts added: {added_total}")
    print(f"   Total concepts now: {total}")
    for sid in sorted(merged):
        print(f"   {sid:6s}: {len(merged[sid])} concepts")


if __name__ == "__main__":
    data_js = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DATA_JS
    merge_into_data_js(build_all(), data_js)
