#!/usr/bin/env python3
"""Round 4 — OS, ALGO, DM deep coverage. Run: python tools/expand_r4.py data.js"""
import json, re, sys
from pathlib import Path

DEFAULT_DATA_JS = Path(__file__).resolve().parents[2] / "public" / "data" / "data.js"

OS_R4 = [
  {"id":"fork_exec","name":"fork() & exec()","topic":"Process Management","definition":"fork(): duplicates calling process. exec(): replaces process image with new program.","intuition":"fork = photocopy the process; exec = tear out the copy's pages and paste a new book.","formula":"After fork: parent gets child PID, child gets 0. Both see same code after fork().","difficulty":"medium","importance":8,"exam_trick":"fork() followed by exec() is how shells launch programs.","common_mistake":"After fork(), BOTH parent and child continue executing from the SAME point.","pyq_insight":"GATE: n nested fork() calls creates 2^n - 1 new processes total.","relations":[]},
  {"id":"ipc","name":"Inter-Process Communication (IPC)","topic":"Process Management","definition":"Mechanisms for processes to communicate: pipes, shared memory, message queues, sockets.","intuition":"Processes are isolated — IPC breaks that isolation for collaboration.","formula":"Pipe: unidirectional. Named pipe: bidirectional. Shared memory: fastest IPC (no kernel).","difficulty":"medium","importance":7,"exam_trick":"Shared memory is fastest IPC — no kernel copy. Message passing safer but slower.","common_mistake":"Anonymous pipe works only between related (parent-child) processes.","pyq_insight":"GATE: identify IPC mechanism; compare throughput of shared memory vs pipes.","relations":[]},
  {"id":"critical_section","name":"Critical Section Problem","topic":"Synchronization","definition":"Code section accessing shared data that must not be executed simultaneously by multiple processes.","intuition":"Only one process in the 'room' at a time — the room is the critical section.","formula":"Requirements: Mutual Exclusion, Progress, Bounded Waiting. TSL instruction implements HW lock.","difficulty":"medium","importance":9,"exam_trick":"Software solutions (Peterson's) are for educational purposes; hardware TSL is real-world.","common_mistake":"Disabling interrupts for CS: works for single CPU, DANGEROUS for multiprocessor.","pyq_insight":"GATE: verify if given solution satisfies ME, Progress, Bounded Waiting.","relations":[]},
  {"id":"priority_inversion","name":"Priority Inversion","topic":"Scheduling","definition":"High-priority task waits for resource held by low-priority task — lower task preempted by medium.","intuition":"VIP waits while a regular user holds needed resource, and regular user keeps getting preempted.","formula":"Solution: Priority Inheritance — temporarily boost low-priority task to highest waiter's priority.","difficulty":"hard","importance":7,"exam_trick":"Mars Pathfinder failure was caused by priority inversion. Classic real-world example.","common_mistake":"Priority Inheritance Protocol (PIP) doesn't fully prevent all priority inversion chains.","pyq_insight":"GATE: identify priority inversion scenario; propose priority inheritance solution.","relations":[{"to":"scheduling","type":"depends_on"}]},
  {"id":"rw_problem","name":"Readers-Writers Problem","topic":"Synchronization","definition":"Multiple readers concurrent; writer needs exclusive access.","intuition":"Library: many can read the same book simultaneously; only one person can rewrite it.","formula":"Reader-priority: readers never wait for readers. Writer-priority: writers never wait behind new readers.","difficulty":"hard","importance":8,"exam_trick":"Reader-priority can starve writers. Writer-priority can starve readers.","common_mistake":"Using a simple mutex prevents all concurrency — defeats the purpose.","pyq_insight":"GATE: trace semaphore solution; identify starvation condition in given implementation.","relations":[]},
  {"id":"dining_philosophers","name":"Dining Philosophers","topic":"Synchronization","definition":"5 philosophers share 5 forks; must hold both adjacent forks to eat — classic deadlock scenario.","intuition":"If all pick up left fork simultaneously and wait for right → deadlock!","formula":"Solutions: allow only 4 at table, pick up both atomically, odd-left/even-right, chandy-misra.","difficulty":"hard","importance":7,"exam_trick":"Solution must prevent deadlock AND starvation. Some simple fixes have starvation.","common_mistake":"Picking both forks atomically (critical section) eliminates deadlock but reduces concurrency.","pyq_insight":"GATE: identify deadlock scenario; evaluate which solution property is violated.","relations":[]},
  {"id":"copy_on_write","name":"Copy-On-Write (COW)","topic":"Memory Management","definition":"Parent and child share same pages after fork(); copy is made only when either modifies a page.","intuition":"Don't photocopy the entire book — use the same copy until someone writes in it.","formula":"On write to shared page: OS creates private copy for writing process, updates page table.","difficulty":"medium","importance":7,"exam_trick":"COW makes fork() very cheap. Pages are shared until written — most exec() calls never copy.","common_mistake":"COW copies the PAGE not the entire address space. Only the modified page gets copied.","pyq_insight":"GATE: compute actual page copies in fork()+exec() scenario with COW.","relations":[]},
  {"id":"memory_allocation","name":"Memory Allocation Strategies","topic":"Memory Management","definition":"First-fit, best-fit, worst-fit for allocating variable-size memory blocks.","intuition":"First-fit: use first big enough hole. Best-fit: tightest hole. Worst-fit: biggest hole.","formula":"First-fit fastest. Best-fit: minimizes wasted space per allocation but causes tiny fragments.","difficulty":"medium","importance":7,"exam_trick":"Worst-fit leaves largest 'leftover' hole — keeps big holes available for future requests.","common_mistake":"Best-fit doesn't minimize total fragmentation — it creates many tiny unusable holes.","pyq_insight":"GATE: apply given strategy to hole list; determine if request can be satisfied.","relations":[]},
  {"id":"buddy_system","name":"Buddy Allocation","topic":"Memory Management","definition":"Memory divided in powers of 2. Blocks split/merged in pairs (buddies) to minimize fragmentation.","intuition":"Like splitting a chocolate bar along marked lines — always split in half, merge when both halves free.","formula":"Size always power of 2. Buddy of block at address X of size S: X XOR S.","difficulty":"hard","importance":6,"exam_trick":"Buddy merges are fast — just check if buddy is free. Great for kernel memory.","common_mistake":"Buddy causes internal fragmentation — must allocate next power of 2 even if smaller size needed.","pyq_insight":"GATE: trace buddy allocation/deallocation; compute internal fragmentation.","relations":[]},
  {"id":"working_set","name":"Working Set Model","topic":"Memory Management","definition":"Set of pages a process is actively using in a recent time window Δ.","intuition":"Each process needs its 'working set' in RAM — if not enough frames, thrashing occurs.","formula":"WS_i(t,Δ) = pages referenced in (t-Δ, t]. Total demand = Σ|WS_i|.","difficulty":"hard","importance":8,"exam_trick":"If total demand > physical frames → suspend some processes to prevent thrashing.","common_mistake":"Working set changes over time. Page replacement should also adapt dynamically.","pyq_insight":"GATE: compute working set size for given reference string and window size.","relations":[{"to":"thrashing","type":"depends_on"}]},
  {"id":"tlb_shootdown","name":"TLB Shootdown","topic":"Memory Management","definition":"When a page table entry is modified, all CPU TLBs caching that entry must be invalidated.","intuition":"All cashiers (CPUs) must discard their cached price (TLB entry) when the real price changes.","formula":"IPI (inter-processor interrupt) sent to all CPUs to flush TLB entry. Expensive on multicore.","difficulty":"hard","importance":5,"exam_trick":"TLB shootdown is a key scalability bottleneck for shared virtual memory multiprocessors.","common_mistake":"Single CPU systems don't need TLB shootdown — only relevant for SMP/NUMA.","pyq_insight":"GATE: rarely asked directly; context for multiprocessor cache coherence questions.","relations":[]},
  {"id":"page_fault_handling","name":"Page Fault Handling","topic":"Memory Management","definition":"Hardware trap to OS when process accesses page not in RAM. OS loads page from disk.","intuition":"Book not on your desk: ask librarian (OS) to fetch it from storage (disk).","formula":"Steps: trap→save state→find victim page→disk I/O→update page table→restart instruction.","difficulty":"medium","importance":8,"exam_trick":"Page fault is expensive: disk I/O takes ~10ms. TLB miss is only ~100ns.","common_mistake":"Page fault does NOT crash the program — it's a normal OS mechanism.","pyq_insight":"GATE: compute effective access time with given page fault rate.","relations":[]},
  {"id":"ext_int_fragmentation","name":"Internal vs External Fragmentation","topic":"Memory Management","definition":"Internal: wasted space inside allocated block. External: free space exists but not contiguous.","intuition":"Internal = too-big box with padding. External = enough free space total, but scattered.","formula":"Paging eliminates external fragmentation. Segmentation and contiguous allocation have external.","difficulty":"easy","importance":7,"exam_trick":"Fixed-size allocation (paging) → internal fragmentation. Variable-size → external.","common_mistake":"Compaction can fix external fragmentation but is expensive (move all allocated blocks).","pyq_insight":"GATE: identify fragmentation type for given memory scheme.","relations":[]},
]

ALGO_R4 = [
  {"id":"kadane","name":"Kadane's Algorithm","topic":"Dynamic Programming","definition":"Finds maximum subarray sum in O(n) using a single scan.","intuition":"Track current subarray sum; reset to 0 if it goes negative (no point carrying a loss).","formula":"maxEnd=max(arr[i], maxEnd+arr[i]); maxSoFar=max(maxSoFar,maxEnd). O(n).","difficulty":"medium","importance":7,"exam_trick":"Handles all-negative arrays: answer = maximum single element (don't reset to 0, reset to arr[i]).","common_mistake":"Initializing maxSoFar=0 fails when all elements are negative.","pyq_insight":"GATE: trace Kadane on given array; identify the maximum subarray.","relations":[{"to":"dp","type":"part_of"}]},
  {"id":"edit_distance","name":"Edit Distance (Levenshtein)","topic":"Dynamic Programming","definition":"Minimum insert/delete/replace operations to convert string A to string B.","intuition":"Like correcting a typo: how many single-character fixes to reach the target string.","formula":"dp[i][j]=dp[i-1][j-1] if match, else 1+min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]).","difficulty":"hard","importance":7,"exam_trick":"Edit distance is symmetric: dist(A,B) = dist(B,A). O(mn) time and space.","common_mistake":"Insertion in A = deletion in B. Only 3 operations needed regardless of naming.","pyq_insight":"GATE: fill DP table for given strings; identify minimum operations.","relations":[{"to":"lcs","type":"variant_of"}]},
  {"id":"coin_change","name":"Coin Change Problem","topic":"Dynamic Programming","definition":"Find minimum coins to make amount n, or count all ways to make amount n.","intuition":"DP over all amounts: for each coin, check if using it gives better result.","formula":"Min coins: dp[i]=min(dp[i], dp[i-coin]+1). Ways: dp[i]+=dp[i-coin]. O(n×coins).","difficulty":"medium","importance":8,"exam_trick":"Greedy FAILS for arbitrary denominations. DP is always correct.","common_mistake":"Greedy works ONLY for canonical systems (like {1,5,10,25}). General case needs DP.","pyq_insight":"GATE: compute minimum coins or count ways for given denomination set.","relations":[{"to":"dp","type":"part_of"}]},
  {"id":"tsp","name":"Travelling Salesman Problem","topic":"Complexity","definition":"Find shortest Hamiltonian cycle visiting all n cities exactly once. NP-hard.","intuition":"Salesman visits every city once and returns home — find the cheapest route.","formula":"Exact DP: Held-Karp O(n²2^n). Approx: nearest neighbor, MST-based 2-approx.","difficulty":"hard","importance":8,"exam_trick":"TSP is NP-hard (optimization) and NP-complete (decision version). No known poly-time solution.","common_mistake":"MST-based approximation gives 2× optimal bound. This is a GUARANTEE, not average.","pyq_insight":"GATE: classify TSP as NP; compare brute-force vs Held-Karp complexity.","relations":[{"to":"np_completeness","type":"part_of"}]},
  {"id":"bipartite_matching","name":"Bipartite Matching","topic":"Graph Algorithms","definition":"Maximum matching in bipartite graph where every vertex is matched to at most one on the other side.","intuition":"Assign workers to jobs — maximize number of assignments respecting qualifications.","formula":"Hungarian algorithm: O(n³). Hopcroft-Karp: O(E√V). Max matching = n - max independent set (König).","difficulty":"hard","importance":7,"exam_trick":"König's theorem: in bipartite graphs, max matching = min vertex cover.","common_mistake":"König's theorem is ONLY for bipartite graphs. General graphs use Gallai's theorem.","pyq_insight":"GATE: find maximum matching; apply König's theorem to find minimum vertex cover.","relations":[]},
  {"id":"articulation","name":"Articulation Points & Bridges","topic":"Graph Algorithms","definition":"Articulation point: removal disconnects graph. Bridge: edge whose removal disconnects graph.","intuition":"Critical junctions and roads in a city — remove them and the network splits.","formula":"Tarjan's DFS with discovery time and low-link values. O(V+E).","difficulty":"hard","importance":7,"exam_trick":"Articulation point in DFS tree: root (if ≥2 subtrees) or non-root (if child's low ≥ disc time).","common_mistake":"Every bridge has both endpoints as articulation points — but not every articulation point is endpoint of a bridge.","pyq_insight":"GATE: find articulation points in given graph; determine graph bi-connectivity.","relations":[]},
  {"id":"prim_kruskal_compare","name":"Prim vs Kruskal Comparison","topic":"Graph Algorithms","definition":"Both find MST. Prim grows from one vertex; Kruskal sorts edges globally.","intuition":"Prim = expand a snowball. Kruskal = connect cheapest wires regardless of location.","formula":"Prim (binary heap): O(E log V). Prim (Fibonacci heap): O(E + V log V). Kruskal: O(E log E).","difficulty":"medium","importance":7,"exam_trick":"Dense graph (E≈V²): Prim wins. Sparse graph (E≈V): Kruskal wins.","common_mistake":"Both produce MSTs that may look different but have SAME total weight.","pyq_insight":"GATE: choose algorithm for given density; trace step-by-step; count MST options.","relations":[{"to":"mst","type":"part_of"}]},
  {"id":"avl_rotation","name":"AVL Rotations — Detailed","topic":"Trees","definition":"LL: right rotate. RR: left rotate. LR: left rotate left child, then right rotate root. RL: reverse.","intuition":"Balance a leaning tower by rotating it back to vertical — direction of rotation = direction of lean.","formula":"LL (BF=+2, left child BF≥0): single right rotation. LR (BF=+2, left child BF<0): double rotation.","difficulty":"hard","importance":8,"exam_trick":"Mnemonic: HEAVY SIDE needs rotation TOWARD it. LL heavy on left → rotate RIGHT.","common_mistake":"RL imbalance: right child is left-heavy → right-rotate child first, then left-rotate root.","pyq_insight":"GATE: trace AVL insertion; identify rotation type and draw resulting tree.","relations":[{"to":"avl","type":"part_of"}]},
  {"id":"red_black","name":"Red-Black Trees","topic":"Trees","definition":"Self-balancing BST where nodes are colored red/black with specific coloring invariants.","intuition":"Colors enforce balance: no path from root to leaf can be twice as long as shortest path.","formula":"Properties: root=black, red node's children=black, all root-to-null paths have same black count.","difficulty":"hard","importance":6,"exam_trick":"RB tree height ≤ 2log(n+1). Insertion: O(log n), at most 3 rotations. Deletion: O(log n).","common_mistake":"RB tree is NOT as strictly balanced as AVL — height can be 2× AVL. But rotations are fewer.","pyq_insight":"GATE: verify RB tree properties; occasional rotation question.","relations":[{"to":"avl","type":"variant_of"}]},
  {"id":"divide_conquer","name":"Divide & Conquer","topic":"Algorithm Design","definition":"Split problem into subproblems, solve recursively, combine. Complexity from Master Theorem.","intuition":"Break problem in half repeatedly. Solve small pieces. Stitch results back together.","formula":"T(n)=2T(n/2)+O(n)→O(n log n). T(n)=T(n/2)+O(1)→O(log n).","difficulty":"medium","importance":9,"exam_trick":"Binary search, merge sort, quick sort, Strassen, closest pair — all divide & conquer.","common_mistake":"QuickSort divide is NOT balanced — worst case O(n²) with bad pivot.","pyq_insight":"GATE: write recurrence for given algorithm; solve using Master Theorem.","relations":[]},
  {"id":"randomized","name":"Randomized Algorithms","topic":"Algorithm Design","definition":"Use random choices to simplify or speed up solutions. Las Vegas: always correct. Monte Carlo: probabilistic.","intuition":"Flip a coin to make decisions — eliminates worst-case adversarial inputs.","formula":"QuickSort with random pivot: O(n log n) expected regardless of input.","difficulty":"hard","importance":6,"exam_trick":"Las Vegas: correct with probability 1, runtime is random. Monte Carlo: may be wrong.","common_mistake":"Expected O(n log n) for random QuickSort is NOT the same as O(n log n) worst case.","pyq_insight":"GATE: classify algorithm type; compute expected comparisons for random quicksort.","relations":[]},
  {"id":"approx_algo","name":"Approximation Algorithms","topic":"Complexity","definition":"Polynomial algorithms that guarantee solution within a factor of optimal for NP-hard problems.","intuition":"Can't find perfect solution efficiently — settle for 'good enough' with a quality guarantee.","formula":"ρ-approximation: cost ≤ ρ × OPT. Vertex cover: 2-approx (greedy edge matching).","difficulty":"hard","importance":7,"exam_trick":"Greedy vertex cover: pick edge, add BOTH endpoints — always 2-approximation.","common_mistake":"Approximation ratio ρ≥1 for minimization (cost UP to ρ×OPT). ρ≤1 for maximization.","pyq_insight":"GATE: verify approximation ratio; identify algorithm type for given NP-hard problem.","relations":[{"to":"np_completeness","type":"depends_on"}]},
]

DM_R4 = [
  {"id":"inclusion_exclusion","name":"Inclusion-Exclusion Principle","topic":"Combinatorics","definition":"|A∪B∪C| = |A|+|B|+|C|-|A∩B|-|B∩C|-|A∩C|+|A∩B∩C|.","intuition":"Add all sets, subtract double-counts, add back triple-counts that were over-subtracted.","formula":"For n sets: |A₁∪...∪Aₙ| = Σ|Aᵢ| - Σ|Aᵢ∩Aⱼ| + Σ|Aᵢ∩Aⱼ∩Aₖ| - ... ","difficulty":"medium","importance":8,"exam_trick":"Perfect for 'at least one' probability via P(A∪B) = P(A)+P(B)-P(A∩B).","common_mistake":"For 3 sets forget to ADD BACK the triple intersection after subtracting pairs.","pyq_insight":"GATE: count strings with at least one digit or upper/lowercase — use inclusion-exclusion.","relations":[]},
  {"id":"catalan","name":"Catalan Numbers","topic":"Combinatorics","definition":"Cₙ = C(2n,n)/(n+1). Counts many structures: BSTs, parenthesizations, triangulations.","intuition":"Cₙ counts the number of valid structures of n pairs/elements.","formula":"C₀=1, Cₙ=Σ(k=0 to n-1) Cₖ·Cₙ₋₁₋ₖ. Cₙ = C(2n,n)/(n+1).","difficulty":"medium","importance":9,"exam_trick":"n-key BSTs = Cₙ. Full parenthesizations of n+1 factors = Cₙ. Triangulations = Cₙ₋₂.","common_mistake":"Catalan number for BSTs uses n keys (not n-1). C₅ = 42 BSTs for 5 keys.","pyq_insight":"GATE: count BSTs/paths/matched parentheses using Catalan — very common.","relations":[]},
  {"id":"stirling","name":"Stirling Numbers","topic":"Combinatorics","definition":"S(n,k): ways to partition n elements into k non-empty unlabeled subsets.","intuition":"How many ways to split a class into k study groups (groups are interchangeable).","formula":"S(n,k) = k·S(n-1,k) + S(n-1,k-1). S(n,1)=1, S(n,n)=1.","difficulty":"hard","importance":6,"exam_trick":"Onto functions from n to k elements: k! × S(n,k).","common_mistake":"S(n,k) ≠ C(n,k). Stirling counts PARTITIONS; C(n,k) counts SELECTIONS.","pyq_insight":"GATE: not common but appears as counting onto functions problem.","relations":[]},
  {"id":"partial_order","name":"Partial Orders & Hasse Diagrams","topic":"Set Theory","definition":"Reflexive, antisymmetric, transitive relation (POSET). Hasse diagram omits reflexive/transitive edges.","intuition":"Like 'divisibility': 2|4|8 forms a chain. Hasse diagram shows it as a directed tower.","formula":"Hasse diagram: remove self-loops and edges implied by transitivity.","difficulty":"medium","importance":7,"exam_trick":"Total order: every pair is comparable. Partial order: some pairs may be incomparable.","common_mistake":"Hasse diagram does NOT show self-loops or implied edges — must identify what falls in between.","pyq_insight":"GATE: draw Hasse diagram; find maximal/minimal elements; check total vs partial order.","relations":[{"to":"relations","type":"part_of"}]},
  {"id":"equivalence_class","name":"Equivalence Classes & Partitions","topic":"Set Theory","definition":"Equivalence relation partitions set into disjoint, exhaustive equivalence classes [a].","intuition":"'Same mod 3' groups all integers into {0,3,6,...}, {1,4,7,...}, {2,5,8,...} — 3 perfect groups.","formula":"[a] = {x ∈ A | x R a}. Quotient set A/R = collection of all equivalence classes.","difficulty":"medium","importance":7,"exam_trick":"Number of equivalence classes = number of distinct partitions. Bell number Bₙ counts these.","common_mistake":"Every element belongs to EXACTLY ONE equivalence class — classes are disjoint.","pyq_insight":"GATE: find equivalence classes for given relation; determine if relation is equivalence.","relations":[{"to":"relations","type":"part_of"}]},
  {"id":"planar_graph","name":"Planar Graphs & Euler's Formula","topic":"Graph Theory","definition":"Graph drawable in plane with no edge crossings. Euler: V - E + F = 2 (connected planar).","intuition":"Can you draw the graph without lines crossing? K₄ yes. K₅ no.","formula":"Planar: E ≤ 3V-6. Bipartite planar: E ≤ 2V-4. K₅ and K₃,₃ are minimal non-planar.","difficulty":"hard","importance":8,"exam_trick":"Quick non-planarity check: E > 3V-6 → definitely non-planar. Kuratowski: subdivision of K₅ or K₃,₃.","common_mistake":"Euler's formula V-E+F=2 only for CONNECTED planar graphs. F includes outer/unbounded face.","pyq_insight":"GATE: verify planarity; count faces; apply Euler's formula given V and E.","relations":[{"to":"graph_theory","type":"part_of"}]},
  {"id":"graph_isomorphism","name":"Graph Isomorphism","topic":"Graph Theory","definition":"Two graphs are isomorphic if there's a bijection preserving adjacency. NI (neither P nor NP-complete known).","intuition":"Two different 'drawings' of the same graph — relabel vertices and check if graphs are identical.","formula":"Necessary conditions: same V, E, degree sequence, cycle count — but NOT sufficient.","difficulty":"hard","importance":6,"exam_trick":"Same degree sequence is NECESSARY not SUFFICIENT. Many non-isomorphic graphs share degree sequences.","common_mistake":"Checking degree sequence alone: C₆ and two disjoint C₃ have same degree sequence but different structure.","pyq_insight":"GATE: check if two graphs are isomorphic using invariants.","relations":[]},
  {"id":"ramsey","name":"Ramsey Theory Basics","topic":"Graph Theory","definition":"R(m,n): minimum complete graph size guaranteeing clique of size m or independent set of size n.","intuition":"In any large enough party: either m people all know each other, or n people who are all strangers.","formula":"R(3,3) = 6. Among 6 people, there are always 3 mutual friends or 3 mutual strangers.","difficulty":"hard","importance":5,"exam_trick":"R(3,3)=6 is the only value usually memorized. Bounds: R(m,n) ≤ C(m+n-2, m-1).","common_mistake":"Ramsey guarantees existence — doesn't provide a construction.","pyq_insight":"GATE: conceptual knowledge of R(3,3); rarely asked computationally.","relations":[]},
  {"id":"functions","name":"Functions & Types","topic":"Set Theory","definition":"Function f: A→B assigns each element of A exactly one element of B.","intuition":"One-to-one mapping from inputs to outputs — no input skipped, no input maps to two outputs.","formula":"Injective: one-to-one. Surjective/Onto: every B element has preimage. Bijective: both.","difficulty":"easy","importance":8,"exam_trick":"Number of functions A→B: |B|^|A|. Injective: P(|B|,|A|). Bijective: |A|! if |A|=|B|.","common_mistake":"Injection requires |A| ≤ |B|. Surjection requires |B| ≤ |A|. Both → |A|=|B| (bijection).","pyq_insight":"GATE: count functions satisfying given property; identify function type.","relations":[]},
]

COA_R4 = [
  {"id":"ieee754","name":"IEEE 754 Floating Point","topic":"Number Systems","definition":"Standard for float representation: sign bit, biased exponent, mantissa (significand).","intuition":"Scientific notation in binary: ±1.mantissa × 2^(exponent-bias).","formula":"Single: 1+8+23 bits, bias=127. Double: 1+11+52 bits, bias=1023. Stored: 1.f × 2^(E-bias).","difficulty":"hard","importance":9,"exam_trick":"Implicit leading 1 in mantissa for normalized numbers. Denormalized: exp=0, no leading 1.","common_mistake":"Bias=127 for single, NOT 128. Stored exponent = actual exponent + 127.","pyq_insight":"GATE: convert decimal to IEEE 754; compute represented value; identify precision limits.","relations":[{"to":"number_systems","type":"part_of"}]},
  {"id":"booth","name":"Booth's Algorithm","topic":"Arithmetic Units","definition":"Efficient multiplication algorithm for 2's complement numbers. Handles negative multipliers.","intuition":"Look at pairs of bits: 01→add, 10→subtract, 00/11→no operation. Reduces operations.","formula":"Examine bit and previous bit (Q₋₁). 01: A=A+M. 10: A=A-M. 00/11: no change. Right shift.","difficulty":"hard","importance":7,"exam_trick":"Modified Booth: examine 3 bits at a time → halves number of partial products.","common_mistake":"Initialize Q₋₁=0. Final result is in (A,Q) after n iterations.","pyq_insight":"GATE: trace Booth's algorithm for given operands; compute partial products.","relations":[]},
  {"id":"cache_coherence","name":"Cache Coherence","topic":"Memory Hierarchy","definition":"In multi-processor systems, ensure all caches have consistent view of shared memory.","intuition":"If CPU1 modifies a value, CPU2's cached copy becomes stale — coherence protocol fixes this.","formula":"MESI protocol: Modified, Exclusive, Shared, Invalid states per cache line.","difficulty":"hard","importance":7,"exam_trick":"Write-invalidate: on write, invalidate other copies. Write-update: broadcast new value.","common_mistake":"Cache coherence ≠ memory consistency. Coherence for one location; consistency for ordering.","pyq_insight":"GATE: identify cache state transitions in MESI protocol given access sequence.","relations":[{"to":"cache","type":"part_of"}]},
  {"id":"memory_hierarchy","name":"Memory Hierarchy Design","topic":"Memory Hierarchy","definition":"Levels: registers, L1/L2/L3 cache, DRAM, disk. Each level: larger, slower, cheaper.","intuition":"Hot data travels up toward registers. Cold data stays on disk. Locality drives efficiency.","formula":"Capacity: registers<L1<L2<L3<RAM<disk. Speed inverse. Cost/bit: registers>>disk.","difficulty":"easy","importance":7,"exam_trick":"Temporal locality: reuse recent data. Spatial locality: use nearby data. Both exploited by caches.","common_mistake":"L1 cache is SEPARATE for instructions and data (split cache). L2 usually unified.","pyq_insight":"GATE: compute average access time using weighted sum across memory hierarchy levels.","relations":[{"to":"cache","type":"part_of"}]},
  {"id":"restoring_division","name":"Restoring & Non-Restoring Division","topic":"Arithmetic Units","definition":"Hardware algorithms for integer division producing quotient and remainder.","intuition":"Trial subtraction: subtract divisor; if result negative, restore (add back) and shift.","formula":"Restoring: subtract, check sign; if negative restore and set quotient bit=0. Non-restoring avoids restore step.","difficulty":"hard","importance":6,"exam_trick":"Non-restoring division: if negative shift and ADD divisor. If positive shift and SUBTRACT.","common_mistake":"Initialize accumulator A=0, dividend Q, n iterations where n = dividend bits.","pyq_insight":"GATE: trace restoring division for small numbers; identify quotient and remainder.","relations":[]},
  {"id":"microprogramming","name":"Microprogramming","topic":"CPU Design","definition":"Control unit implemented as ROM storing microinstructions that implement each machine instruction.","intuition":"Each assembly instruction is really a tiny program in the control unit's ROM.","formula":"Horizontal microcode: wide words, one bit per control signal. Vertical: encoded, fewer bits.","difficulty":"hard","importance":5,"exam_trick":"Vertical microprogramming: requires decoder but shorter control words.","common_mistake":"Hardwired control is FASTER than microprogrammed. Microprogrammed is MORE FLEXIBLE.","pyq_insight":"GATE: compare hardwired vs microprogrammed control; identify tradeoffs.","relations":[]},
  {"id":"superscalar","name":"Superscalar & VLIW","topic":"CPU Design","definition":"Superscalar: CPU fetches and executes multiple instructions per cycle dynamically. VLIW: compiler schedules multiple instructions per cycle statically.","intuition":"Superscalar: smart CPU decides what to run in parallel. VLIW: smart compiler decides at compile time.","formula":"Superscalar: IPC > 1. VLIW: bundle = fixed-width packet with multiple independent instructions.","difficulty":"hard","importance":6,"exam_trick":"VLIW requires smart compiler — no runtime dependency checking needed.","common_mistake":"IPC > 1 needs TRUE instruction-level parallelism — data dependencies limit this.","pyq_insight":"GATE: compare ILP techniques; identify which is hardware vs software speculation.","relations":[{"to":"pipeline","type":"depends_on"}]},
]

def build_all():
    return {"os": OS_R4, "algo": ALGO_R4, "dm": DM_R4, "coa": COA_R4}

def merge(new_concepts, data_js_path):
    text = data_js_path.read_text(encoding="utf-8", errors="ignore")
    existing = {}
    m = re.search(r'const CONCEPTS=(\{[\s\S]*?\});\n', text)
    if m:
        try: existing = json.loads(m.group(1))
        except: pass
    merged = dict(existing); added = 0
    for sid, concepts in new_concepts.items():
        if sid not in merged: merged[sid] = []
        seen = {c['id'] for c in merged[sid]}
        new = [c for c in concepts if c['id'] not in seen]
        merged[sid].extend(new); added += len(new)
    payload = json.dumps(merged, ensure_ascii=False, indent=2)
    new_block = f"\n// ═══ CONCEPTS DATA ═══\nconst CONCEPTS={payload};\n"
    text = re.sub(r'\n// ═══ CONCEPTS DATA ═══\nconst CONCEPTS=\{[\s\S]*?\};\n', new_block, text)
    if new_block not in text:
        text = text.replace("// ═══ REVISION CONTENT DATA ═══", new_block + "\n// ═══ REVISION CONTENT DATA ═══", 1)
    data_js_path.write_text(text, encoding="utf-8")
    total = sum(len(v) for v in merged.values())
    print(f"✅ R4 done! Added: {added}  Total: {total}")
    for s in sorted(merged): print(f"   {s:6s}: {len(merged[s])}")

if __name__ == "__main__":
    merge(build_all(), Path(sys.argv[1]) if len(sys.argv)>1 else DEFAULT_DATA_JS)
