#!/usr/bin/env python3
"""
GATE Concept Intelligence Engine — Phase 2: Concept Generator
Produces a curated CONCEPTS object for data.js, covering all GATE CS subjects.
Each concept has: definition, intuition, formula, exam_trick, common_mistake, pyq_insight, relations.
"""
import json
import re
from pathlib import Path

DEFAULT_DATA_JS = Path(__file__).resolve().parents[2] / "public" / "data" / "data.js"

# ═══════════════════════════════════════════════════════════════════
# CURATED GATE CONCEPT TAXONOMY
# ═══════════════════════════════════════════════════════════════════

CONCEPTS = {

# ─────────────────────────────────────────
#  ENGINEERING MATHEMATICS — CALCULUS
# ─────────────────────────────────────────
"calc": [
  {"id":"limit","name":"Limits","topic":"Calculus","definition":"Value a function approaches as input tends to a point.","intuition":"Describes behavior near a point, not at it.","formula":"lim(x→a) f(x) = L","difficulty":"medium","importance":8,"exam_trick":"If direct substitution gives 0/0, use L'Hôpital's rule.","common_mistake":"Assuming limit equals the function value at that point.","pyq_insight":"GATE asks limit of integral forms using Newton-Leibnitz rule.","relations":[{"to":"continuity","type":"depends_on"}]},
  {"id":"continuity","name":"Continuity","topic":"Calculus","definition":"Function is continuous at a if limit = f(a) = defined.","intuition":"No breaks, holes, or jumps in the graph.","formula":"lim(x→a⁻) = lim(x→a⁺) = f(a)","difficulty":"medium","importance":8,"exam_trick":"Differentiability implies continuity; converse NOT true.","common_mistake":"Thinking |x| is not continuous — it IS continuous at 0.","pyq_insight":"Often asks: 'Is this function differentiable or only continuous?'","relations":[{"to":"differentiability","type":"depends_on"}]},
  {"id":"differentiability","name":"Differentiability","topic":"Calculus","definition":"Function has a well-defined derivative at a point.","intuition":"Tangent line exists and is unique at that point.","formula":"f'(x) = lim(h→0) [f(x+h) - f(x)] / h","difficulty":"medium","importance":8,"exam_trick":"Check LHD = RHD. |x| is NOT differentiable at x=0.","common_mistake":"Assuming continuity implies differentiability.","pyq_insight":"Classic trap: sin|x| at x=0, |x|² at x=0.","relations":[{"to":"lhopital","type":"depends_on"}]},
  {"id":"lhopital","name":"L'Hôpital's Rule","topic":"Calculus","definition":"Resolves 0/0 or ∞/∞ limits by differentiating numerator and denominator.","intuition":"If ratio is indeterminate, the ratio of derivatives gives the true limit.","formula":"lim f/g = lim f'/g' when form is 0/0 or ∞/∞","difficulty":"medium","importance":9,"exam_trick":"Apply ONLY when form is 0/0 or ∞/∞. Check form first!","common_mistake":"Applying to 1×∞ or 0⁰ directly without converting.","pyq_insight":"Very common in GATE EM section. lim(x→0) sinx/x = 1.","relations":[{"to":"taylor_series","type":"depends_on"}]},
  {"id":"taylor_series","name":"Taylor & Maclaurin Series","topic":"Calculus","definition":"Infinite polynomial representation of a smooth function around a point.","intuition":"Any smooth curve can be perfectly approximated by powers of (x-a).","formula":"f(x) = Σ f⁽ⁿ⁾(a)(x-a)ⁿ/n! ; Maclaurin when a=0","difficulty":"hard","importance":9,"exam_trick":"Coefficient of xⁿ in expansion = f⁽ⁿ⁾(0)/n!","common_mistake":"Maclaurin ≠ Taylor in general — it's Taylor at a=0.","pyq_insight":"GATE asks: find coeff of x³ in expansion of f(x).","relations":[]},
  {"id":"maxima_minima","name":"Maxima & Minima","topic":"Calculus","definition":"Points where derivative is zero; determined by second derivative test.","intuition":"Peaks and valleys of the function where slope is flat.","formula":"f'(x)=0; max if f''<0, min if f''>0","difficulty":"medium","importance":8,"exam_trick":"If f''(c)=0, test higher derivatives or check sign change.","common_mistake":"Not checking boundary values for global extrema.","pyq_insight":"Often appears in optimization problems in GATE EM.","relations":[]},
  {"id":"newton_leibnitz","name":"Newton-Leibnitz Rule","topic":"Calculus","definition":"Differentiates a definite integral with variable limits.","intuition":"Chain rule applied to each boundary of the integral.","formula":"d/dx[∫φ^ψ f(t)dt] = f(ψ)ψ' - f(φ)φ'","difficulty":"hard","importance":9,"exam_trick":"Use when limit question has integral in numerator/denominator.","common_mistake":"Forgetting to multiply by derivative of the limit bound.","pyq_insight":"Very high frequency 2-mark GATE question combined with L'Hôpital.","relations":[]},
  {"id":"ilate","name":"Integration by Parts (ILATE)","topic":"Calculus","definition":"Technique for integrating a product of two functions.","intuition":"Trade a harder integral for an easier one by differentiating one part.","formula":"∫f·g dx = f·∫g dx - ∫[f'·∫g dx] dx","difficulty":"medium","importance":7,"exam_trick":"ILATE order: Inverse, Log, Algebraic, Trig, Exponential. First = u.","common_mistake":"Applying ILATE in wrong order — always pick leftmost in ILATE as u.","pyq_insight":"Standard result: ∫x·eˣ dx = (x-1)eˣ + C.","relations":[]},
],

# ─────────────────────────────────────────
#  ENGINEERING MATHEMATICS — LINEAR ALGEBRA
# ─────────────────────────────────────────
"la": [
  {"id":"matrix_rank","name":"Rank of a Matrix","topic":"Linear Algebra","definition":"Number of linearly independent rows (or columns) in a matrix.","intuition":"Measures how much 'information' the matrix carries.","formula":"rank(A) = pivot count in row echelon form","difficulty":"medium","importance":9,"exam_trick":"Elementary row ops do NOT change rank.","common_mistake":"Assuming rank(A)=rank(Aᵀ) is surprising — they are ALWAYS equal.","pyq_insight":"Used to determine uniqueness/existence of solutions to Ax=b.","relations":[{"to":"eigenvalues","type":"depends_on"}]},
  {"id":"eigenvalues","name":"Eigenvalues & Eigenvectors","topic":"Linear Algebra","definition":"Scalars and vectors satisfying Av = λv.","intuition":"Directions that only stretch/shrink under the transformation A.","formula":"det(A - λI) = 0 to find eigenvalues","difficulty":"hard","importance":10,"exam_trick":"Sum of eigenvalues = trace(A), Product = det(A). Quick shortcut!","common_mistake":"Eigenvectors of A and Aᵀ are NOT the same (eigenvalues are same).","pyq_insight":"Most asked topic in LA. Expect 1-2 questions every year.","relations":[{"to":"cayley_hamilton","type":"depends_on"}]},
  {"id":"cayley_hamilton","name":"Cayley-Hamilton Theorem","topic":"Linear Algebra","definition":"Every matrix satisfies its own characteristic polynomial.","intuition":"Substitute A itself in place of λ in the characteristic equation.","formula":"p(λ) = det(A-λI) = 0 → p(A) = 0","difficulty":"hard","importance":8,"exam_trick":"Use to find A⁻¹ = (1/det(A)) × (A term from char. equation).","common_mistake":"Forgetting to set p(A)=0, not p(λ)=0.","pyq_insight":"GATE uses this to find A⁻¹ or powers of A efficiently.","relations":[]},
  {"id":"system_equations","name":"System of Linear Equations","topic":"Linear Algebra","definition":"Set of equations Ax=b. Solution exists based on ranks of A and [A|b].","intuition":"Geometrically, each equation is a hyperplane. Solution = intersection.","formula":"ρ(A)=ρ([A|b])=n → unique; <n → infinite; ρ(A)≠ρ([A|b]) → none","difficulty":"medium","importance":9,"exam_trick":"Always check augmented matrix rank vs coefficient matrix rank.","common_mistake":"Homogeneous system Ax=0 always has at least trivial solution x=0.","pyq_insight":"GATE directly asks: unique/infinite/no solution — standard 2-marker.","relations":[]},
  {"id":"rank_nullity","name":"Rank-Nullity Theorem","topic":"Linear Algebra","definition":"rank(A) + nullity(A) = number of columns of A.","intuition":"The column space dimension + null space dimension = total space.","formula":"rank + nullity = n (columns)","difficulty":"medium","importance":7,"exam_trick":"nullity = dimension of solution space of Ax=0.","common_mistake":"nullity = n - rank (must use COLUMN count, not row count).","pyq_insight":"Used in GATE to count free variables in underdetermined systems.","relations":[]},
],

# ─────────────────────────────────────────
#  ENGINEERING MATHEMATICS — PROBABILITY
# ─────────────────────────────────────────
"ps": [
  {"id":"bayes","name":"Bayes' Theorem","topic":"Probability","definition":"Reverses conditional probability: P(A|B) using P(B|A).","intuition":"Update prior belief based on new evidence.","formula":"P(Eᵢ|A) = P(Eᵢ)P(A|Eᵢ) / ΣP(Eⱼ)P(A|Eⱼ)","difficulty":"hard","importance":9,"exam_trick":"Build a probability tree. P(A|B) ≠ P(B|A) — Bayes bridges the gap.","common_mistake":"Confusing prior and posterior probability.","pyq_insight":"GATE: sensitivity/specificity → find P(disease|positive test).","relations":[]},
  {"id":"distributions","name":"Probability Distributions","topic":"Statistics","definition":"Functions mapping outcomes to probabilities (PMF for discrete, PDF for continuous).","intuition":"Describes how likely different values of a random variable are.","formula":"Binomial: C(n,r)pʳqⁿ⁻ʳ; Poisson: e⁻λλʳ/r!; Normal: bell curve","difficulty":"medium","importance":9,"exam_trick":"For Poisson: mean = variance = λ. Very commonly tested.","common_mistake":"Poisson variance = λ (not √λ, which is the std dev).","pyq_insight":"GATE often picks between Binomial and Poisson — rare events → Poisson.","relations":[]},
  {"id":"expectation_variance","name":"Expectation & Variance","topic":"Statistics","definition":"Expected value = weighted average of outcomes; Variance = spread measure.","intuition":"E[X] is the long-run average; Var(X) measures how spread-out values are.","formula":"E[aX+b]=aE[X]+b; Var(aX+b)=a²Var(X); Var(X)=E[X²]-(E[X])²","difficulty":"medium","importance":8,"exam_trick":"Var(X+Y) = Var(X)+Var(Y) only if X,Y are independent.","common_mistake":"Adding variances for non-independent variables without covariance term.","pyq_insight":"GATE directly tests Var formula and E[g(X)] calculation from PMF.","relations":[]},
],

# ─────────────────────────────────────────
#  DISCRETE MATHEMATICS
# ─────────────────────────────────────────
"dm": [
  {"id":"propositional_logic","name":"Propositional Logic","topic":"Logic","definition":"Study of logical statements (propositions) and their truth values.","intuition":"Building blocks of reasoning: AND, OR, NOT, IMPLIES, IFF.","formula":"p→q ≡ ¬p∨q; p↔q ≡ (p→q)∧(q→p); De Morgan: ¬(p∧q)≡¬p∨¬q","difficulty":"medium","importance":9,"exam_trick":"Contrapositive of p→q is ¬q→¬p — always equivalent!","common_mistake":"Converse (q→p) and inverse (¬p→¬q) are NOT equivalent to p→q.","pyq_insight":"GATE tests: identify tautologies, simplify expressions, implication.","relations":[{"to":"first_order_logic","type":"depends_on"}]},
  {"id":"first_order_logic","name":"First Order Logic (FOL)","topic":"Logic","definition":"Extends propositional logic with predicates, variables, and quantifiers.","intuition":"Universal (∀) says 'for all'; Existential (∃) says 'there exists at least one'.","formula":"∀x P(x) → ¬∃x ¬P(x); ∃x P(x) → ¬∀x ¬P(x)","difficulty":"hard","importance":7,"exam_trick":"Negate quantifiers by flipping ∀↔∃ and negating inner predicate.","common_mistake":"'∀x P(x) → Q(x)' is NOT same as '(∀x P(x)) → (∀x Q(x))'.","pyq_insight":"GATE gives a statement and asks for its logical equivalent.","relations":[]},
  {"id":"graph_theory","name":"Graph Theory Basics","topic":"Graph Theory","definition":"Study of vertices (nodes) and edges (connections) between them.","intuition":"Models networks, relationships, and paths between entities.","formula":"Handshaking: Σdeg(v) = 2|E|; Euler: V-E+F=2 (planar connected)","difficulty":"medium","importance":10,"exam_trick":"Number of odd-degree vertices is ALWAYS even (handshaking lemma).","common_mistake":"V-E+F=2 applies ONLY to connected planar graphs.","pyq_insight":"Most asked DM topic. Planar, chromatic number, Eulerian paths every year.","relations":[{"to":"trees","type":"depends_on"}]},
  {"id":"trees","name":"Trees & Spanning Trees","topic":"Graph Theory","definition":"Connected acyclic graph; spanning tree covers all vertices with minimum edges.","intuition":"Tree is the most efficient way to connect all nodes without creating cycles.","formula":"Tree: n vertices, n-1 edges. Spanning trees of Kₙ = n^(n-2) (Cayley).","difficulty":"medium","importance":9,"exam_trick":"Tree = connected + acyclic = connected + n-1 edges (any two imply third).","common_mistake":"Assuming unique path in tree — it IS unique, but that's the property.","pyq_insight":"GATE asks: number of spanning trees, height of complete binary tree.","relations":[]},
  {"id":"relations","name":"Relations & Closure","topic":"Set Theory","definition":"A relation R on set A is a subset of A×A. Properties: reflexive, symmetric, transitive.","intuition":"A relation is a rule that pairs elements. Equivalence = RST. Partial order = RAT.","formula":"Transitive closure by Warshall's algorithm: O(n³)","difficulty":"medium","importance":8,"exam_trick":"Equivalence relation partitions the set into disjoint equivalence classes.","common_mistake":"Anti-symmetric ≠ not symmetric. A relation can be both!","pyq_insight":"GATE: classify relation, find closure, count equivalence classes.","relations":[]},
  {"id":"recurrence","name":"Recurrence Relations","topic":"Combinatorics","definition":"Defines sequence where each term is expressed in terms of preceding terms.","intuition":"Like a program loop — solve by unrolling or using Master Theorem.","formula":"a(n) = a(n-1) + a(n-2); solve by characteristic equation method","difficulty":"hard","importance":8,"exam_trick":"For T(n)=aT(n/b)+f(n): use Master Theorem directly.","common_mistake":"Applying Master Theorem when regularity condition fails in Case 3.","pyq_insight":"Appears in GATE algo section; also in DM for counting structures.","relations":[]},
  {"id":"counting","name":"Counting & Combinatorics","topic":"Combinatorics","definition":"Counting arrangements and selections with/without repetition and order.","intuition":"Permutation = order matters; Combination = order doesn't matter.","formula":"P(n,r)=n!/(n-r)!; C(n,r)=n!/[r!(n-r)!]; Derangements: D(n)=n![1-1/1!+...+(-1)ⁿ/n!]","difficulty":"medium","importance":8,"exam_trick":"Circular permutation = (n-1)! If clockwise=anti-clockwise: divide by 2.","common_mistake":"Combination with repetition: C(n+r-1,r), NOT C(n,r).","pyq_insight":"GATE: count BSTs with n keys = Catalan(n) = C(2n,n)/(n+1).","relations":[]},
],

# ─────────────────────────────────────────
#  DIGITAL LOGIC
# ─────────────────────────────────────────
"dl": [
  {"id":"boolean_algebra","name":"Boolean Algebra","topic":"Boolean Logic","definition":"Algebraic system where variables are true/false (1/0) and operations are AND, OR, NOT.","intuition":"All digital circuits are ultimately combinations of AND, OR, NOT.","formula":"De Morgan: (A·B)' = A'+B'; (A+B)' = A'·B'; Absorption: A+AB = A","difficulty":"medium","importance":9,"exam_trick":"NAND and NOR are universal gates — can implement any function.","common_mistake":"Duality: swap AND↔OR, 0↔1. This is different from complement.","pyq_insight":"GATE asks for minimal SOP/POS using K-map with don't cares.","relations":[{"to":"kmap","type":"depends_on"}]},
  {"id":"kmap","name":"Karnaugh Map (K-map)","topic":"Boolean Logic","definition":"Visual method to minimize Boolean expressions by grouping minterms.","intuition":"Bigger groups → fewer literals → simpler circuit.","formula":"Groups must be powers of 2 (1,2,4,8). Wrap around edges.","difficulty":"medium","importance":10,"exam_trick":"Always create LARGEST possible groups. Don't cares can be 0 or 1.","common_mistake":"Forgetting to find ALL prime implicants, then select Essential PIs.","pyq_insight":"Appears every GATE year. 2-4 marks. Never skip this topic.","relations":[{"to":"combinational_circuits","type":"depends_on"}]},
  {"id":"combinational_circuits","name":"Combinational Circuits","topic":"Circuit Design","definition":"Output depends only on current inputs — no memory elements.","intuition":"Pure logic function: MUX, decoder, adder, comparator.","formula":"Full adder: Sum=A⊕B⊕Cin; Cout=AB+BCin+ACin","difficulty":"medium","importance":8,"exam_trick":"2ⁿ:1 MUX with n select lines implements ANY n-variable function.","common_mistake":"MUX is select-driven — data comes from inputs, not select lines.","pyq_insight":"GATE: implement function using 4:1 MUX with one input as variable.","relations":[{"to":"sequential_circuits","type":"contrasts_with"}]},
  {"id":"sequential_circuits","name":"Sequential Circuits & Flip-Flops","topic":"Circuit Design","definition":"Output depends on current inputs AND past state (memory element present).","intuition":"Circuit with a 'memory' — flip-flops store the current state.","formula":"JK FF: Q(t+1)=JQ'+K'Q; D FF: Q(t+1)=D; T FF: Q(t+1)=T⊕Q","difficulty":"hard","importance":9,"exam_trick":"SR FF has forbidden state S=R=1. JK resolves this by toggling.","common_mistake":"Mealy output depends on state+input; Moore output depends only on state.","pyq_insight":"GATE asks flip-flop conversion using excitation tables + K-map.","relations":[]},
  {"id":"number_systems","name":"Number Systems & Arithmetic","topic":"Number Theory","definition":"Different bases for representing numbers: binary, octal, hex, BCD.","intuition":"All computer data is ultimately binary. Conversions are reversible.","formula":"2's comp range: -2^(n-1) to 2^(n-1)-1. Overflow = Cin(MSB) ⊕ Cout(MSB).","difficulty":"easy","importance":7,"exam_trick":"Hex↔Binary: group 4 bits. Octal↔Binary: group 3 bits.","common_mistake":"BCD: only 0000-1001 valid. If sum>9, add 0110 (6) to correct.","pyq_insight":"GATE tests 2's complement arithmetic and overflow detection.","relations":[]},
  {"id":"fsm","name":"Finite State Machines","topic":"Automata","definition":"Model of computation with states, transitions, inputs, and outputs.","intuition":"Like a vending machine — current state + input determines next state + output.","formula":"Mealy: output on transitions. Moore: output on states.","difficulty":"hard","importance":8,"exam_trick":"Minimize FSM: find equivalent states using table-filling method.","common_mistake":"Mealy → Moore conversion increases state count.","pyq_insight":"GATE: design sequence detector, find minimal DFA equivalent.","relations":[]},
],

# ─────────────────────────────────────────
#  COMPUTER ORGANIZATION & ARCHITECTURE
# ─────────────────────────────────────────
"coa": [
  {"id":"pipeline","name":"Instruction Pipelining","topic":"CPU Design","definition":"Overlaps execution of multiple instructions in stages.","intuition":"Like an assembly line: while one instruction executes, the next is decoded.","formula":"Speedup = k·n/(k+n-1); k=stages, n=instructions","difficulty":"hard","importance":10,"exam_trick":"With infinite instructions, speedup → k (number of stages).","common_mistake":"Stalls reduce throughput. CPI_actual = CPI_ideal + stall_cycles/instruction.","pyq_insight":"Most tested COA topic. Stall cycles, forwarding, CPI calculation.","relations":[{"to":"hazards","type":"depends_on"}]},
  {"id":"hazards","name":"Pipeline Hazards","topic":"CPU Design","definition":"Conditions that prevent next instruction from executing in the next cycle.","intuition":"Data dependency, resource conflicts, and branch decisions cause delays.","formula":"RAW: instruction n needs result of n-1 before it's ready.","difficulty":"hard","importance":9,"exam_trick":"RAW is the only TRUE data hazard. WAW and WAR can be eliminated by renaming.","common_mistake":"All three hazard types exist (structural, data, control) — not just data.","pyq_insight":"GATE: given dependency graph, find number of stall cycles.","relations":[]},
  {"id":"cache","name":"Cache Memory","topic":"Memory Hierarchy","definition":"Fast, small memory between CPU and RAM to reduce average access time.","intuition":"Most frequently accessed data is kept in faster, smaller cache.","formula":"AMAT = Hit time + Miss rate × Miss penalty; EAT = h·Tc + (1-h)·Tm","difficulty":"hard","importance":10,"exam_trick":"Simultaneous lookup: EAT = h·Tc+(1-h)·Tm. Sequential: Tc+(1-h)·Tm.","common_mistake":"Cache EAT model type (simultaneous vs sequential) must match problem statement.","pyq_insight":"Appears every GATE year. Multi-level cache AMAT, direct-mapped conflict misses.","relations":[{"to":"virtual_memory","type":"similar_to"}]},
  {"id":"virtual_memory","name":"Virtual Memory & Paging","topic":"Memory Hierarchy","definition":"Technique allowing processes to use more memory than physically available.","intuition":"Each process gets its own virtual address space; OS maps pages to frames.","formula":"TLB EAT: α(TLB+Tm)+(1-α)(TLB+2Tm) [α=TLB hit ratio]","difficulty":"hard","importance":9,"exam_trick":"TLB hit still requires 1 memory access (for data). Miss requires 2+.","common_mistake":"Page fault brings data from disk. TLB miss is just a page table walk (RAM).","pyq_insight":"GATE: compute EAT with TLB hit ratio and page fault rate combined.","relations":[]},
  {"id":"addressing_modes","name":"Addressing Modes","topic":"Instruction Set","definition":"Methods of specifying the operand location in an instruction.","intuition":"Different modes trade-off speed vs flexibility for accessing data.","formula":"Immediate: value in instruction. Direct: address in instruction. Indexed: base+offset.","difficulty":"medium","importance":7,"exam_trick":"Register indirect is fast — no memory access for address calculation.","common_mistake":"Indirect addressing requires an extra memory access (fetch address, then fetch data).","pyq_insight":"GATE: identify addressing mode from instruction format given.","relations":[]},
],

# ─────────────────────────────────────────
#  PROGRAMMING & DATA STRUCTURES
# ─────────────────────────────────────────
"pds": [
  {"id":"trees_bst","name":"Binary Search Trees (BST)","topic":"Trees","definition":"Binary tree where left subtree < node < right subtree for all nodes.","intuition":"Sorted binary tree. Inorder traversal always gives sorted sequence.","formula":"Search/Insert/Delete: O(h). Balanced (AVL): h=O(log n). Worst case: h=n (sorted input).","difficulty":"medium","importance":10,"exam_trick":"Inorder of BST = sorted order. Number of BSTs with n keys = Catalan(n).","common_mistake":"Plain BST can degenerate to O(n) — always ask if 'balanced' is specified.","pyq_insight":"GATE: insert sequence, find height. Or: minimum keys for AVL of height h.","relations":[{"to":"avl","type":"depends_on"}]},
  {"id":"avl","name":"AVL Trees (Balanced BST)","topic":"Trees","definition":"Self-balancing BST where height difference between subtrees ≤ 1.","intuition":"After every insert/delete, rotations restore balance factor ∈ {-1,0,1}.","formula":"BF = height(left) - height(right) ∈ {-1,0,1}; Min nodes: N(h)=N(h-1)+N(h-2)+1","difficulty":"hard","importance":8,"exam_trick":"4 rotation types: LL, RR, LR, RL. LR = left rotate child, then right rotate root.","common_mistake":"LL imbalance needs RIGHT rotation (not left). Think of the heavy subtree side.","pyq_insight":"GATE: trace AVL insertions, identify rotation type and resulting tree.","relations":[]},
  {"id":"heaps","name":"Heaps & Priority Queue","topic":"Trees","definition":"Complete binary tree satisfying heap property (max or min at root).","intuition":"Parent always dominates children. Root is always the extreme value.","formula":"Build heap: O(n). Insert/extract: O(log n). Height: ⌊log₂n⌋.","difficulty":"medium","importance":8,"exam_trick":"Build heap is O(n), NOT O(n log n). This is a very common trap.","common_mistake":"Heap does NOT support O(log n) arbitrary delete without knowing the index.","pyq_insight":"GATE: heapify trace, heap sort comparisons, or priority queue simulation.","relations":[]},
  {"id":"hashing","name":"Hashing & Collision","topic":"Hashing","definition":"Maps keys to array indices via a hash function. Collisions handled by chaining or open addressing.","intuition":"Direct access by computing array index from key — ideally O(1).","formula":"Load factor α = n/m. Chaining: O(1+α). Open addressing fails when α≥1.","difficulty":"medium","importance":8,"exam_trick":"Linear probing: primary clustering. Quadratic: secondary. Double hashing: best.","common_mistake":"Open addressing max load factor < 1. Chaining can go above 1.","pyq_insight":"GATE: trace hash table with specific function and collision resolution.","relations":[]},
  {"id":"graph_traversal","name":"Graph Traversal (BFS & DFS)","topic":"Graph Algorithms","definition":"Systematic exploration of graph vertices. BFS uses queue; DFS uses stack/recursion.","intuition":"BFS = level-by-level exploration (shortest path). DFS = go deep before backtracking.","formula":"Both: O(V+E) time, O(V) space. BFS gives shortest path in unweighted graphs.","difficulty":"medium","importance":9,"exam_trick":"BFS tree = shortest-path tree. DFS finds cycles, topological sort, SCCs.","common_mistake":"DFS does NOT find shortest paths. Use BFS for unweighted shortest path.","pyq_insight":"GATE: DFS/BFS traversal order, back edges (cycles), cross edges.","relations":[]},
  {"id":"sorting","name":"Sorting Algorithms","topic":"Algorithms","definition":"Rearranging elements in a specified order using comparison or distribution-based methods.","intuition":"Trade-offs between stability, in-place, worst-case, and average-case complexity.","formula":"Merge: O(n log n) worst, stable. Quick: O(n²) worst, O(n log n) avg, in-place, unstable.","difficulty":"medium","importance":9,"exam_trick":"Heap sort: O(n log n) ALL cases, in-place, unstable. Only algo with guaranteed O(n log n).","common_mistake":"Quick sort is NOT O(n log n) guaranteed — sorted input → O(n²) with naive pivot.","pyq_insight":"GATE: worst case comparisons, sorted input behavior, stability requirements.","relations":[]},
],

# ─────────────────────────────────────────
#  ALGORITHMS
# ─────────────────────────────────────────
"algo": [
  {"id":"master_theorem","name":"Master Theorem","topic":"Analysis","definition":"Closed-form solution for divide-and-conquer recurrences of form T(n)=aT(n/b)+f(n).","intuition":"Compare f(n) to n^(log_b a). Whichever dominates, determines complexity.","formula":"c=log_b(a); Case1: f=O(n^(c-ε))→T=O(nᶜ); Case2: f=Θ(nᶜ)→T=O(nᶜlogn); Case3: f=Ω(n^(c+ε))→T=O(f(n))","difficulty":"hard","importance":10,"exam_trick":"Case 2 is most common: T(n)=2T(n/2)+n → O(n log n).","common_mistake":"Case 3 also needs 'regularity condition' — check if af(n/b) ≤ cf(n).","pyq_insight":"GATE: every year. 1-2 recurrences to solve using Master Theorem.","relations":[]},
  {"id":"dijkstra","name":"Dijkstra's Algorithm","topic":"Graph Algorithms","definition":"Single-source shortest path for graphs with non-negative weights.","intuition":"Greedily expand the nearest unvisited node. Like ripples expanding in water.","formula":"O((V+E)log V) with binary heap; O(V²) without heap","difficulty":"hard","importance":9,"exam_trick":"Dijkstra FAILS with negative weights. Use Bellman-Ford instead.","common_mistake":"Dijkstra does NOT work on graphs with negative edges — even one breaks it.","pyq_insight":"GATE: trace algorithm, find shortest path distance, identify visited order.","relations":[{"to":"bellman_ford","type":"contrasts_with"}]},
  {"id":"bellman_ford","name":"Bellman-Ford Algorithm","topic":"Graph Algorithms","definition":"Single-source shortest path supporting negative weights; detects negative cycles.","intuition":"Relax all edges V-1 times. If still improving after V-1 iterations → negative cycle.","formula":"O(VE) time. V-1 relaxation passes required.","difficulty":"hard","importance":8,"exam_trick":"V-1 passes are necessary and sufficient for a graph with no negative cycles.","common_mistake":"Bellman-Ford works with negative WEIGHTS but NOT negative CYCLES.","pyq_insight":"GATE: given graph with negative edge, use Bellman-Ford trace.","relations":[]},
  {"id":"mst","name":"Minimum Spanning Tree","topic":"Graph Algorithms","definition":"Spanning tree of weighted graph with minimum total edge weight.","intuition":"Connect all nodes with minimum total wire length.","formula":"Kruskal: O(E log E) — sort edges, greedy union-find. Prim: O(E log V) — grow from one vertex.","difficulty":"medium","importance":8,"exam_trick":"For dense graphs: Prim better. For sparse: Kruskal better.","common_mistake":"MST is NOT unique if edge weights are distinct — actually it IS unique then.","pyq_insight":"GATE: trace Kruskal/Prim step by step. Number of MSTs where weights repeat.","relations":[]},
  {"id":"dp","name":"Dynamic Programming","topic":"Optimization","definition":"Solves complex problems by breaking into subproblems and memoizing results.","intuition":"Store and reuse subproblem solutions instead of recomputing them.","formula":"LCS: dp[i][j]=dp[i-1][j-1]+1 if match, else max. Knapsack: dp[i][w]=max(exclude, include).","difficulty":"hard","importance":10,"exam_trick":"Check: overlapping subproblems + optimal substructure → DP applies.","common_mistake":"0/1 Knapsack CANNOT be solved greedily. Fractional knapsack CAN.","pyq_insight":"GATE: LCS, edit distance, matrix chain, coin change — all standard DP questions.","relations":[]},
  {"id":"np_completeness","name":"NP-Completeness","topic":"Complexity","definition":"Class of decision problems where solution is verifiable in polynomial time but not necessarily solvable.","intuition":"If any NP-complete problem had a poly-time solution, ALL NP problems would be solvable.","formula":"P ⊆ NP. NP-hard: at least as hard as NP-complete. P=NP is open.","difficulty":"hard","importance":8,"exam_trick":"Show NP-completeness: reduce a KNOWN NP-complete problem to your problem.","common_mistake":"NP-hard problems are NOT necessarily in NP (they may not be decision problems).","pyq_insight":"GATE: classify problem as P, NP, NP-complete, NP-hard, or undecidable.","relations":[]},
],

# ─────────────────────────────────────────
#  THEORY OF COMPUTATION
# ─────────────────────────────────────────
"toc": [
  {"id":"dfa_nfa","name":"DFA & NFA","topic":"Finite Automata","definition":"DFA: deterministic (one transition per symbol). NFA: can have multiple/epsilon transitions.","intuition":"Both accept exactly the class of Regular languages. NFA is more compact.","formula":"NFA→DFA via subset construction. DFA states ≤ 2^(NFA states).","difficulty":"medium","importance":10,"exam_trick":"NFA to DFA conversion: worst case = 2ⁿ states but usually much fewer.","common_mistake":"NFA and DFA have SAME power — both recognize regular languages only.","pyq_insight":"Most asked TOC topic. Minimize DFA using table-filling (Myhill-Nerode).","relations":[{"to":"regular_languages","type":"depends_on"}]},
  {"id":"regular_languages","name":"Regular Languages","topic":"Formal Languages","definition":"Languages recognized by DFA/NFA, equivalently described by regular expressions.","intuition":"Can be described with finite memory — no counting needed.","formula":"Closed under: union, intersection, complement, concatenation, Kleene star.","difficulty":"medium","importance":9,"exam_trick":"Any language requiring counting (e.g., aⁿbⁿ) is NOT regular.","common_mistake":"Pumping lemma can only DISPROVE regularity — passing it doesn't prove regularity.","pyq_insight":"GATE: prove non-regularity using pumping lemma. Closure property questions.","relations":[{"to":"cfl","type":"depends_on"}]},
  {"id":"cfl","name":"Context-Free Languages (CFL)","topic":"Formal Languages","definition":"Languages recognized by Pushdown Automata; described by Context-Free Grammars.","intuition":"Can count ONE thing — like matching parentheses or aⁿbⁿ.","formula":"CFL NOT closed under intersection or complement. CFL ∩ Regular = CFL.","difficulty":"hard","importance":9,"exam_trick":"CFL ∩ CFL is NOT necessarily CFL. This is a classic closure trap.","common_mistake":"Assuming aⁿbⁿcⁿ is CFL — it is NOT (it's Context-Sensitive).","pyq_insight":"GATE: write CFG for given language, identify closure properties.","relations":[{"to":"turing_machines","type":"depends_on"}]},
  {"id":"turing_machines","name":"Turing Machines & Decidability","topic":"Computability","definition":"Most powerful computational model. Accepts Recursively Enumerable (RE) languages.","intuition":"TM = infinite tape + read/write head. Can simulate any algorithm.","formula":"Decidable: TM always halts. RE: TM halts on accept, may loop on reject.","difficulty":"hard","importance":8,"exam_trick":"Rice's theorem: any non-trivial property of TM-recognized languages is UNDECIDABLE.","common_mistake":"Complement of RE may not be RE. Complement of Recursive = Recursive.","pyq_insight":"GATE: classify halting problem, membership problem — decidable or not.","relations":[]},
  {"id":"pumping_lemma","name":"Pumping Lemma","topic":"Formal Languages","definition":"Necessary condition for regularity/CFL-ness. Used to DISPROVE membership in a language class.","intuition":"If a language is regular, any long-enough string can be 'pumped' and stay in the language.","formula":"Regular: w=xyz, |xy|≤p, |y|≥1, ∀i≥0: xyⁿz∈L. CFL: two segments pumped: uvⁿxyⁿz∈L.","difficulty":"hard","importance":8,"exam_trick":"To disprove: assume L is regular, find a string that fails pumping for ALL decompositions.","common_mistake":"Pumping works → language IS regular? NO. It's a necessary, not sufficient condition.","pyq_insight":"GATE: apply pumping lemma to show aⁿbⁿ, ww, primes are not regular.","relations":[]},
],

# ─────────────────────────────────────────
#  COMPILER DESIGN
# ─────────────────────────────────────────
"cd": [
  {"id":"lexical_analysis","name":"Lexical Analysis","topic":"Compiler Phases","definition":"First phase: converts character stream to token stream using regular expressions.","intuition":"Breaking source code into meaningful units (keywords, identifiers, numbers).","formula":"Token pattern = regular expression → NFA → DFA (for implementation)","difficulty":"medium","importance":7,"exam_trick":"Lexer removes comments and whitespace. Reports lexical errors (invalid tokens).","common_mistake":"Lexer checks syntax? NO — only token structure. Parser checks syntax.","pyq_insight":"GATE: recognize strings/tokens using given regex or automaton.","relations":[{"to":"parsing","type":"depends_on"}]},
  {"id":"parsing","name":"Parsing (Syntax Analysis)","topic":"Compiler Phases","definition":"Verifies grammatical structure of token stream; builds parse tree or AST.","intuition":"Parser ensures tokens form valid sentences according to the grammar.","formula":"LL(1) table: M[A,a]=production. LR power: LR(0)⊂SLR(1)⊂LALR(1)⊂LR(1).","difficulty":"hard","importance":10,"exam_trick":"LL(1) ← weakest. LR(1) ← most powerful. LALR(1) = practical choice (yacc/bison).","common_mistake":"Ambiguous grammar→ grammar is ambiguous; NOT language is ambiguous.","pyq_insight":"GATE every year: FIRST, FOLLOW computation; LL(1) table; LR conflict detection.","relations":[{"to":"first_follow","type":"depends_on"}]},
  {"id":"first_follow","name":"FIRST & FOLLOW Sets","topic":"Parsing","definition":"FIRST(α): terminals that can start a string derived from α. FOLLOW(A): terminals that can follow A.","intuition":"FIRST tells what can come FROM a non-terminal. FOLLOW tells what comes AFTER it.","formula":"$ always in FOLLOW(start symbol). If ε∈FIRST(α): add FOLLOW(A) to table entry M[A,b].","difficulty":"hard","importance":10,"exam_trick":"For FOLLOW: always check all productions where A appears on RHS.","common_mistake":"Forgetting to propagate ε through FIRST computation when production can derive ε.","pyq_insight":"GATE: compute FIRST/FOLLOW and build LL(1) parsing table from grammar.","relations":[]},
  {"id":"optimization","name":"Code Optimization","topic":"Compiler Backend","definition":"Transformations that improve code efficiency without changing behavior.","intuition":"Eliminate redundancy, move invariants out of loops, propagate constants.","formula":"Peephole: local. CSE, dead code, constant prop/fold: global. Loop-invariant: loop opt.","difficulty":"hard","importance":7,"exam_trick":"Loop-invariant code motion: computation same every iteration → move before loop.","common_mistake":"Dead code ≠ unreachable code. Dead = computed but never used. Both should be removed.","pyq_insight":"GATE: identify optimization technique applicable to given code fragment.","relations":[]},
],

# ─────────────────────────────────────────
#  OPERATING SYSTEMS
# ─────────────────────────────────────────
"os": [
  {"id":"process","name":"Process & Process States","topic":"Process Management","definition":"Instance of a program in execution. Has its own memory space, PCB, and execution context.","intuition":"Thread of execution with private memory — isolated from other processes.","formula":"States: New → Ready → Running → (Waiting or Terminated). Transition on I/O, interrupt, preemption.","difficulty":"medium","importance":8,"exam_trick":"Fork() creates exact copy. Parent and child both run after fork.","common_mistake":"Zombie: child exits, parent not called wait(). Orphan: parent dies first.","pyq_insight":"GATE: count processes created by nested fork() calls.","relations":[{"to":"scheduling","type":"depends_on"}]},
  {"id":"scheduling","name":"CPU Scheduling","topic":"Process Management","definition":"Algorithm to decide which process gets CPU from the ready queue.","intuition":"Balance fairness, throughput, and response time across competing processes.","formula":"TAT = Completion - Arrival; Waiting = TAT - Burst; Response = First_run - Arrival","difficulty":"medium","importance":10,"exam_trick":"SJF minimizes avg wait (non-preemptive). SRTF minimizes overall avg TAT.","common_mistake":"RR quantum too small → context switch overhead; too large → degenerates to FCFS.","pyq_insight":"GATE: draw Gantt chart, compute avg waiting time for mixed arrival processes.","relations":[{"to":"deadlock","type":"depends_on"}]},
  {"id":"deadlock","name":"Deadlock","topic":"Synchronization","definition":"Circular wait among processes where each holds resources the other needs.","intuition":"Four horsemen: Mutual Exclusion, Hold-and-Wait, No Preemption, Circular Wait.","formula":"Banker's Algorithm: Need = Max - Allocation. Check safe state before granting.","difficulty":"hard","importance":10,"exam_trick":"Prevention: negate any ONE Coffman condition. Detection: build wait-for graph.","common_mistake":"Avoiding deadlock requires advance knowledge of max needs. Detection allows occurrence.","pyq_insight":"GATE: Banker's algorithm safe sequence, resource allocation graph, deadlock detection.","relations":[{"to":"synchronization","type":"depends_on"}]},
  {"id":"synchronization","name":"Synchronization & Semaphores","topic":"Synchronization","definition":"Mechanisms to coordinate concurrent access to shared resources.","intuition":"Semaphore is an integer counter with atomic wait/signal operations.","formula":"wait(S): S--; if S<0: block. signal(S): S++; if S≤0: unblock one.","difficulty":"hard","importance":9,"exam_trick":"Binary semaphore = mutex (S∈{0,1}). Counting semaphore for resource count.","common_mistake":"Semaphore value can be NEGATIVE — |S| = number of blocked processes.","pyq_insight":"GATE: producer-consumer, readers-writers with given semaphore operations.","relations":[]},
  {"id":"page_replacement","name":"Page Replacement Algorithms","topic":"Memory Management","definition":"Policy to choose which page to evict when a page fault occurs and memory is full.","intuition":"Best policy minimizes future page faults — impractical but baseline.","formula":"FIFO, LRU (stack algorithm), Optimal (theoretical). Belady's anomaly: only FIFO exhibits it.","difficulty":"hard","importance":9,"exam_trick":"LRU, Optimal are 'stack algorithms' — more frames → never more faults.","common_mistake":"Belady's anomaly: MORE frames → MORE page faults. ONLY happens with FIFO!","pyq_insight":"GATE: trace LRU/FIFO/Optimal on reference string, count page faults.","relations":[]},
  {"id":"file_systems","name":"File Systems & Allocation","topic":"Storage","definition":"Structure for organizing and storing data on disk; maps files to disk blocks.","intuition":"FAT linkage through table; Indexed allocation via inode. UNIX uses inodes.","formula":"Inode: 12 direct + 1 single indirect + 1 double + 1 triple indirect blocks","difficulty":"medium","importance":7,"exam_trick":"Contiguous: fast sequential, suffers external fragmentation. Linked: no fragm, slow random.","common_mistake":"Indexed allocation is NOT contiguous — blocks can be scattered.","pyq_insight":"GATE: compute max file size given filesystem parameters (block size, pointer size).","relations":[]},
],

# ─────────────────────────────────────────
#  DBMS
# ─────────────────────────────────────────
"dbms": [
  {"id":"normalization","name":"Normalization & FDs","topic":"Relational Model","definition":"Process of eliminating data redundancy by organizing tables according to functional dependencies.","intuition":"Each table should store facts about exactly ONE thing — no duplication.","formula":"1NF: atomic. 2NF: -partial FDs. 3NF: -transitive FDs. BCNF: every determant=superkey.","difficulty":"hard","importance":10,"exam_trick":"BCNF ⊂ 3NF ⊂ 2NF ⊂ 1NF. BCNF may LOSE dependency preservation (but not 3NF).","common_mistake":"BCNF always gives lossless decomposition but may not preserve all FDs.","pyq_insight":"GATE: find candidate key, identify highest NF, decompose to BCNF/3NF.","relations":[{"to":"transactions","type":"depends_on"}]},
  {"id":"transactions","name":"Transactions & ACID","topic":"Transaction Management","definition":"Sequence of operations forming a logical unit of work with ACID properties.","intuition":"Either ALL operations succeed (commit) or ALL fail and are undone (rollback).","formula":"ACID: Atomicity, Consistency, Isolation, Durability. 2PL guarantees serializability.","difficulty":"hard","importance":9,"exam_trick":"Strict 2PL = 2PL + hold all locks until commit. Prevents cascading rollback.","common_mistake":"2-phase locking has Growing and Shrinking phases — once you release, cannot acquire.","pyq_insight":"GATE: build precedence graph, check if schedule is conflict-serializable.","relations":[{"to":"indexing","type":"depends_on"}]},
  {"id":"indexing","name":"Indexing & B+ Trees","topic":"Storage","definition":"Data structure to speed up search queries. B+ Tree is the dominant index structure.","intuition":"Like a sorted dictionary index — narrow down location without scanning everything.","formula":"B+ tree height: O(log_p n), where p=order. Internal nodes hold only keys; leaves hold data.","difficulty":"medium","importance":8,"exam_trick":"B+ tree: data ONLY in leaves. B-tree: data in ALL nodes. B+ better for range scans.","common_mistake":"Dense index: entry per record. Sparse index: entry per block (requires sorted file).","pyq_insight":"GATE: compute B+ tree height for given parameters, trace insertion/deletion.","relations":[]},
  {"id":"relational_algebra","name":"Relational Algebra","topic":"Query Processing","definition":"Formal query language for relational databases using set operations and derived operators.","intuition":"σ selects rows, π selects columns, ⋈ joins tables, - finds differences.","formula":"σ: selection. π: projection. ×: Cartesian. ∪: union. -: difference. ⋈: natural join.","difficulty":"medium","importance":8,"exam_trick":"Division (÷) finds rows matching ALL values in target — like universal quantifier.","common_mistake":"Natural join removes duplicate columns; equi-join keeps both copies.","pyq_insight":"GATE: convert SQL to relational algebra or evaluate RA expression on given tables.","relations":[]},
],

# ─────────────────────────────────────────
#  COMPUTER NETWORKS
# ─────────────────────────────────────────
"cn": [
  {"id":"osi_model","name":"OSI & TCP/IP Model","topic":"Network Models","definition":"Layered reference models for network communication. OSI has 7 layers; TCP/IP has 4-5.","intuition":"Each layer adds a 'header' (encapsulation) and hands to the layer below for sending.","formula":"OSI: Physical, DataLink, Network, Transport, Session, Presentation, Application.","difficulty":"medium","importance":7,"exam_trick":"TCP/IP merges Session+Presentation+Application into one Application layer.","common_mistake":"HTTP is Application layer. IP is Network. TCP is Transport. Ethernet is DataLink.","pyq_insight":"GATE: identify which layer a protocol belongs to (DNS, ARP, ICMP are tricky ones).","relations":[{"to":"sliding_window","type":"depends_on"}]},
  {"id":"sliding_window","name":"Sliding Window Protocols","topic":"Data Link Layer","definition":"Flow control protocols allowing multiple outstanding unacknowledged frames.","intuition":"Sender has a 'window' of frames it can send without waiting for ACKs.","formula":"GBN: Sender window ≤ 2ᵏ-1, Receiver=1. SR: Both windows ≤ 2^(k-1).","difficulty":"hard","importance":10,"exam_trick":"GBN window size = 2ᵏ-1 (not 2ᵏ) to avoid ambiguity. SR = half the sequence space each.","common_mistake":"GBN: receiver throws away all out-of-order frames. SR: receiver buffers them.","pyq_insight":"GATE: compute window size, efficiency, throughput for given Tp and Tt.","relations":[{"to":"ip_subnetting","type":"depends_on"}]},
  {"id":"ip_subnetting","name":"IP Addressing & Subnetting","topic":"Network Layer","definition":"IPv4 addresses divided into network and host portions. Subnetting borrows host bits.","intuition":"Like splitting a building into apartments — same building (network), different units (hosts).","formula":"Subnets = 2^n; Hosts/subnet = 2^h - 2; Block size = 2^(32-prefix)","difficulty":"medium","importance":9,"exam_trick":"Network address: all host bits = 0. Broadcast: all host bits = 1. Both unusable.","common_mistake":"CIDR /n: first n bits are NETWORK. Last (32-n) bits are HOST.","pyq_insight":"GATE: given IP and mask, find network address, broadcast, usable host count.","relations":[{"to":"tcp_flow","type":"depends_on"}]},
  {"id":"tcp_flow","name":"TCP & Congestion Control","topic":"Transport Layer","definition":"Reliable, connection-oriented protocol with flow control and congestion avoidance.","intuition":"TCP is like a courteous driver — slows down when traffic is heavy.","formula":"Slow start: cwnd doubles/RTT. Cong. avoidance: +1 MSS/RTT. On loss: ssthresh=cwnd/2.","difficulty":"hard","importance":9,"exam_trick":"On triple dup ACK: fast recovery (cwnd=ssthresh). On timeout: restart slow start (cwnd=1).","common_mistake":"'Slow start' isn't slow — cwnd doubles each RTT (exponential growth).","pyq_insight":"GATE: trace cwnd over multiple RTTs with given loss events.","relations":[]},
  {"id":"routing","name":"Routing Algorithms","topic":"Network Layer","definition":"Algorithms to determine optimal path for data packets through a network.","intuition":"Each router acts locally (DV) or with full topology knowledge (LS).","formula":"Distance Vector (Bellman-Ford based): Dv(y) = minₓ{c(v,x)+Dₓ(y)}. Link State: Dijkstra.","difficulty":"hard","importance":8,"exam_trick":"DV has count-to-infinity problem. LS has full topology — no count-to-infinity.","common_mistake":"RIP uses DV. OSPF uses LS. BGP is path-vector (exterior gateway protocol).","pyq_insight":"GATE: apply routing algorithm to given network, compute routing table.","relations":[]},
],

# ─────────────────────────────────────────
#  GENERAL APTITUDE
# ─────────────────────────────────────────
"ga": [
  {"id":"work_time","name":"Time, Work & Pipes","topic":"Arithmetic","definition":"Rate-based problems where combined work = sum of individual rates.","intuition":"Convert everything to RATES (work per unit time) and then add/subtract.","formula":"Rate of A = 1/a per day. Combined = 1/a + 1/b. Time = 1/combined.","difficulty":"easy","importance":8,"exam_trick":"Emptying pipe subtracts from filling rate. Always work with rates.","common_mistake":"Adding days directly: wrong! Always add rates (1/a + 1/b), then invert.","pyq_insight":"Appears in GA section. 1-2 questions per year.","relations":[]},
  {"id":"speed_distance","name":"Speed, Distance & Time","topic":"Arithmetic","definition":"Fundamental kinematic relationships. Relative speed for trains crossing/chasing.","intuition":"Everything reduces to: Distance = Speed × Time.","formula":"Avg speed (equal dist): 2ab/(a+b). Relative speed: same dir = |v₁-v₂|; opp = v₁+v₂","difficulty":"easy","importance":8,"exam_trick":"For equal distances, NEVER average speeds — use HM formula 2ab/(a+b).","common_mistake":"Simply averaging speeds gives wrong answer for equal-distance trips.","pyq_insight":"GATE GA: train problems (crossing poles, platforms, each other).","relations":[]},
  {"id":"critical_reasoning","name":"Critical Reasoning","topic":"Verbal","definition":"Analyzing arguments to identify assumptions, strengths, and weaknesses.","intuition":"Find the logical gap in the argument. Strengthener fills it; Weakener attacks it.","formula":"Assumption bridges premise to conclusion. Conclusion + Assumption → follows logically.","difficulty":"medium","importance":7,"exam_trick":"Weaken: attack the unstated assumption. Strengthen: provide new supporting evidence.","common_mistake":"Confusing conclusion with a premise — conclusion is the CLAIM, premises are EVIDENCE.","pyq_insight":"GATE GA: 2-4 marks of reading comprehension and critical reasoning every year.","relations":[]},
],
}

# ═══════════════════════════════════════════════════════════════════
# GENERATE JS OUTPUT
# ═══════════════════════════════════════════════════════════════════

def generate_js(concepts_dict):
    """Converts the CONCEPTS dict to a JS const string."""
    payload = json.dumps(concepts_dict, ensure_ascii=False, indent=2)
    return f"\n// ═══ CONCEPTS DATA ═══\nconst CONCEPTS={payload};\n"


def inject_into_data_js(concepts_dict, data_js_path: Path):
    text = data_js_path.read_text(encoding="utf-8", errors="ignore")

    new_block = generate_js(concepts_dict)

    # If CONCEPTS already exists — replace it
    if "const CONCEPTS=" in text:
        text = re.sub(
            r'\n// ═══ CONCEPTS DATA ═══\nconst CONCEPTS=\{[\s\S]*?\};\n',
            new_block,
            text
        )
    else:
        # Insert before REVISION CONTENT DATA
        marker = "// ═══ REVISION CONTENT DATA ═══"
        if marker in text:
            text = text.replace(marker, new_block + "\n" + marker)
        else:
            text += "\n" + new_block

    data_js_path.write_text(text, encoding="utf-8")


def count_concepts(concepts_dict):
    total = sum(len(v) for v in concepts_dict.values())
    print(f"\n✅ Concept Engine Complete!")
    print(f"   Total concepts: {total}")
    print(f"\nConcepts by subject:")
    for sid in sorted(concepts_dict.keys()):
        print(f"   {sid:6s}: {len(concepts_dict[sid])} concepts")


if __name__ == "__main__":
    import sys
    data_js = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DATA_JS
    inject_into_data_js(CONCEPTS, data_js)
    count_concepts(CONCEPTS)
    print(f"\nInjected into: {data_js}")
