#!/usr/bin/env python3
"""
Concept Engine v3 — Round 3 expansion.
Adds 100+ concepts for DL, COA, PDS, DM, CD, LA, PS, GA, Calc.
Run: python tools/expand_concepts_r3.py data.js
"""
import json, re, sys
from pathlib import Path

DEFAULT_DATA_JS = Path(__file__).resolve().parents[2] / "data" / "data.js"

DL_CONCEPTS = [
  {"id":"hazards_dl","name":"Hazards in Combinational Circuits","topic":"Circuit Design","definition":"Unwanted transient output glitches caused by unequal propagation delays.","intuition":"Two paths to same output with different speeds — one arrives before the other causing a glitch.","formula":"Static-1 hazard: output should stay 1 but glitches 0. Fix: add consensus terms in K-map.","difficulty":"hard","importance":7,"exam_trick":"Add redundant prime implicant covering transition between two groups in K-map to eliminate hazard.","common_mistake":"Hazards exist only in COMBINATIONAL circuits. Sequential circuits handle this with clocking.","pyq_insight":"GATE: identify hazard in circuit; apply K-map fix.","relations":[{"to":"kmap","type":"depends_on"}]},
  {"id":"encoder_decoder","name":"Encoders & Decoders","topic":"Combinational Circuits","definition":"Encoder: 2^n inputs → n outputs. Decoder: n inputs → 2^n outputs (one hot).","intuition":"Encoder compresses, decoder expands. Like zip/unzip for digital signals.","formula":"Priority encoder: highest priority input determines output. Enable pin for cascading.","difficulty":"medium","importance":7,"exam_trick":"Decoder + OR gates implements any combinational function. MUX is universal function generator.","common_mistake":"Decoder output is ONE-HOT (exactly one output is 1). Encoder does the opposite.","pyq_insight":"GATE: implement Boolean function using decoder and OR gates.","relations":[{"to":"combinational_circuits","type":"part_of"}]},
  {"id":"registers","name":"Shift Registers","topic":"Sequential Circuits","definition":"Chain of flip-flops sharing a clock. Data shifts left or right each clock cycle.","intuition":"Bucket brigade — data passes from one flip-flop to the next each tick.","formula":"SISO: serial in/out. SIPO: serial in, parallel out. PISO: parallel in, serial out. PIPO: register.","difficulty":"medium","importance":7,"exam_trick":"n-bit shift register delays data by n clock cycles. Used in serial transmission.","common_mistake":"PIPO is just n D flip-flops in parallel — no shifting. It's a simple register.","pyq_insight":"GATE: trace shift register output for given input sequence and initial state.","relations":[{"to":"sequential_circuits","type":"part_of"}]},
  {"id":"counters","name":"Counters","topic":"Sequential Circuits","definition":"Sequential circuit that cycles through a fixed sequence of states.","intuition":"Like a digital odometer — counts up (or down) and wraps around.","formula":"Ripple counter: n FFs → mod-2^n. Synchronous: all FFs clocked together. Mod-N: reset at N.","difficulty":"medium","importance":8,"exam_trick":"Ripple counter: delay = n × t_FF (cascaded). Synchronous counter: delay = 1 × t_FF.","common_mistake":"Ripple counter is ASYNCHRONOUS — FFs don't all clock simultaneously. Glitches possible.","pyq_insight":"GATE: design mod-N counter; trace state sequence; compute propagation delay.","relations":[{"to":"sequential_circuits","type":"part_of"}]},
  {"id":"pla_pal","name":"PLA & PAL","topic":"Programmable Logic","definition":"PLA: programmable AND + programmable OR. PAL: programmable AND + fixed OR.","intuition":"PLA is fully flexible; PAL is faster (fixed OR plane reduces delay).","formula":"PLA size: n inputs, k product terms, m outputs. PAL: n inputs, fixed OR fanin.","difficulty":"medium","importance":6,"exam_trick":"FPGA supersedes both PLA/PAL in modern design. GATE still occasionally asks PLA basics.","common_mistake":"ROM implements any function (2^n minterms). PLA implements functions with fewer terms.","pyq_insight":"GATE: compute PLA size; compare with ROM implementation for given function.","relations":[]},
  {"id":"multiplexer_logic","name":"MUX as Universal Logic","topic":"Combinational Circuits","definition":"A 2^n:1 MUX with n select lines can implement ANY n-variable Boolean function.","intuition":"Connect function truth table column directly to MUX data inputs — inputs select the output.","formula":"4:1 MUX (2 select lines) implements any 2-variable function. 8:1 MUX: any 3-variable.","difficulty":"medium","importance":9,"exam_trick":"With 1 variable on data inputs: (n-1)-variable select lines → n-variable function possible.","common_mistake":"For 'reduced MUX' method: put one variable on data lines; others on select — be systematic.","pyq_insight":"GATE: implement F(A,B,C) using 4:1 MUX — extremely common question type.","relations":[{"to":"combinational_circuits","type":"part_of"}]},
]

COA_CONCEPTS = [
  {"id":"risc_cisc","name":"RISC vs CISC","topic":"Instruction Set","definition":"RISC: simple uniform instructions, load/store architecture. CISC: complex variable-length instructions.","intuition":"RISC = many simple fast moves. CISC = fewer but more powerful moves.","formula":"RISC: more instructions per program, fewer clock cycles per instruction. Net effect similar.","difficulty":"medium","importance":8,"exam_trick":"RISC: fixed format, simple addressing, large register file. CISC: variable format, memory-to-memory ops.","common_mistake":"RISC programs are NOT always smaller — more instructions needed for same computation.","pyq_insight":"GATE: classify instruction features as RISC or CISC. Pipelining easier with RISC.","relations":[]},
  {"id":"interrupts","name":"Interrupts & DMA","topic":"I/O Systems","definition":"Interrupt: hardware signals CPU to stop and handle an event. DMA: device transfers data directly to memory without CPU.","intuition":"Interrupt = phone ringing while working. DMA = courier delivers package without bothering you.","formula":"DMA cycle stealing: DMA takes bus cycles from CPU. Bus bandwidth shared.","difficulty":"medium","importance":7,"exam_trick":"DMA reduces CPU overhead for large transfers. Interrupt-driven I/O better for small transfers.","common_mistake":"DMA doesn't eliminate interrupts — DMA controller interrupts CPU when transfer is DONE.","pyq_insight":"GATE: compare polling vs interrupt-driven vs DMA efficiency for given scenarios.","relations":[]},
  {"id":"instruction_format","name":"Instruction Format & Encoding","topic":"Instruction Set","definition":"Binary encoding of operation, addressing mode, and operand information.","intuition":"Every CPU instruction is a binary recipe: what to do, where operands are, where to store.","formula":"Fixed-length (RISC): 32 bits. Variable-length (CISC): 1-15 bytes.","difficulty":"medium","importance":7,"exam_trick":"Operand encoding affects instruction count. Fewer operand bits = fewer addressable registers.","common_mistake":"Zero-address: stack-based. One-address: accumulator. Two-address: destination modified. Three: separate dest.","pyq_insight":"GATE: decode instruction bits; compute number of instructions given encoding constraints.","relations":[]},
  {"id":"cache_mapping","name":"Cache Mapping & Miss Types","topic":"Memory Hierarchy","definition":"Direct mapped, fully associative, set-associative are the three cache placement policies.","intuition":"Direct = one bucket per address. Fully assoc = any bucket. Set assoc = fixed group of buckets.","formula":"Block offset = log2(block_size). Set index = log2(n_sets). Tag = remaining bits.","difficulty":"hard","importance":9,"exam_trick":"3 C's of misses: Cold (compulsory), Capacity, Conflict. Only Cold exists in fully associative.","common_mistake":"Higher associativity reduces conflict misses but increases hit time (more comparisons).","pyq_insight":"GATE: compute tag/index/offset bits. Determine miss type. Compute miss rate.","relations":[{"to":"cache","type":"part_of"}]},
  {"id":"memory_interleaving","name":"Memory Interleaving","topic":"Memory Hierarchy","definition":"Spreading consecutive memory addresses across multiple memory banks to allow parallel access.","intuition":"Instead of one checkout lane, use multiple — customers (memory requests) served in parallel.","formula":"With k banks: effective bandwidth ≈ k × single bank bandwidth for sequential access.","difficulty":"hard","importance":6,"exam_trick":"High-order interleaving: consecutive banks hold consecutive large blocks. Low-order: consecutive words.","common_mistake":"Interleaving helps sequential (stride-1) access. Stride-k access may serialize if k = bank count.","pyq_insight":"GATE: compute effective memory bandwidth with n-way interleaving.","relations":[]},
  {"id":"branch_prediction","name":"Branch Prediction","topic":"CPU Design","definition":"Predict branch outcome before evaluation to keep pipeline full.","intuition":"Guess the likely branch direction in advance; if wrong, flush pipeline and restart.","formula":"Misprediction penalty = k cycles flushed (k = stages between fetch and execute).","difficulty":"hard","importance":8,"exam_trick":"2-bit saturating counter prediction achieves ~90% accuracy on loops.","common_mistake":"Branch prediction doesn't eliminate the penalty — just makes mispredictions rare.","pyq_insight":"GATE: compute effective CPI with branch prediction given misprediction rate and penalty.","relations":[{"to":"hazards","type":"part_of"}]},
  {"id":"out_of_order","name":"Out-of-Order Execution","topic":"CPU Design","definition":"CPU executes instructions in a different order than program order to avoid stalls.","intuition":"If instruction 3 is waiting for data, execute instructions 4 and 5 first if they're ready.","formula":"Tomasulo's algorithm: register renaming eliminates WAW and WAR hazards.","difficulty":"hard","importance":6,"exam_trick":"Tomasulo + ROB (Reorder Buffer) maintains precise exceptions despite out-of-order execution.","common_mistake":"Out-of-order execution still COMMITS in order (via ROB). Only execution is out-of-order.","pyq_insight":"GATE: conceptual — identify which hazards OOO execution eliminates.","relations":[{"to":"hazards","type":"depends_on"}]},
]

PDS_CONCEPTS = [
  {"id":"linked_list","name":"Linked Lists","topic":"Linear Data Structures","definition":"Collection of nodes where each has data and pointer to next node.","intuition":"Train of cars — each car links to the next; easy to add/remove cars anywhere.","formula":"Insert/delete: O(1) if position known. Search: O(n). No random access.","difficulty":"easy","importance":7,"exam_trick":"Singly linked: O(n) to find previous. Doubly linked: O(1) to access previous.","common_mistake":"Linked list insert at known position is O(1) but FINDING that position is O(n).","pyq_insight":"GATE: reverse linked list in-place, detect loop (Floyd's cycle detection), merge sorted lists.","relations":[]},
  {"id":"stack_apps","name":"Stack Applications","topic":"Linear Data Structures","definition":"LIFO structure for expression evaluation, function calls, backtracking.","intuition":"Stack of plates — last placed, first removed. Natural for nested/recursive structure.","formula":"Infix→Postfix: O(n). Postfix eval: O(n). Recursion simulation: O(depth).","difficulty":"medium","importance":8,"exam_trick":"Balanced parentheses: push opens, pop for closes and match. Stack is standard approach.","common_mistake":"Infix operator precedence must be properly encoded in algorithm.","pyq_insight":"GATE: trace postfix evaluation; convert infix to postfix; check balanced brackets.","relations":[]},
  {"id":"trie","name":"Trie (Prefix Tree)","topic":"Trees","definition":"Tree for storing strings where each node represents a character. Prefix sharing saves space.","intuition":"Like a dictionary organized by letter — all words starting with 'ca' share same branch.","formula":"Insert/search: O(L) where L = string length. Space: O(|alphabet| × |total chars|).","difficulty":"medium","importance":6,"exam_trick":"Trie is optimal for prefix-based queries. NOT efficient for arbitrary substring search.","common_mistake":"Each node has up to |alphabet| children pointers. Can be memory intensive.","pyq_insight":"GATE: count distinct prefixes, find all strings with given prefix, or autocomplete.","relations":[]},
  {"id":"disjoint_set","name":"Union-Find (Disjoint Set Union)","topic":"Data Structures","definition":"Data structure tracking elements partitioned into non-overlapping sets.","intuition":"Friend groups — find who's in same group; merge two groups together.","formula":"With path compression + union by rank: O(α(n)) per operation (nearly O(1)).","difficulty":"medium","importance":8,"exam_trick":"Used in Kruskal's MST to detect cycles. Union by rank prevents skewed trees.","common_mistake":"Without optimizations: O(n) per operation. With both path compression + rank: O(α(n)).","pyq_insight":"GATE: trace union-find operations; apply to Kruskal's algorithm cycle detection.","relations":[]},
  {"id":"btree","name":"B-Trees","topic":"Trees","definition":"Self-balancing multi-way tree for disk-based storage. Order m: each node has up to m children.","intuition":"Like a fat balanced tree — wider nodes reduce height, minimize disk I/O.","formula":"B-tree of order m: each internal node has ⌈m/2⌉ to m children. Height: O(log_m n).","difficulty":"hard","importance":7,"exam_trick":"B-tree vs B+ tree: B-tree stores data everywhere; B+ tree only in leaves (better for scan).","common_mistake":"'Order' definition varies in literature. GATE uses the standard: max children = order m.","pyq_insight":"GATE: insert into B-tree, identify split point, compute height for n keys.","relations":[{"to":"indexing","type":"part_of"}]},
  {"id":"graph_structures","name":"Graph Data Structures","topic":"Graph Algorithms","definition":"Adjacency matrix: O(V²) space. Adjacency list: O(V+E) space. Best choice depends on density.","intuition":"Matrix: fast edge lookup. List: fast neighbor traversal. Dense graph → matrix. Sparse → list.","formula":"Adj matrix: O(V²). Adj list: O(V+E). Edge query: O(1) vs O(degree).","difficulty":"easy","importance":7,"exam_trick":"Adjacency list is ALWAYS preferred for sparse graphs. Matrix wastes memory.","common_mistake":"For weighted graph, adjacency list stores (neighbor, weight) pairs.","pyq_insight":"GATE: choose representation given graph density; compute storage for given V and E.","relations":[]},
  {"id":"heap_impl","name":"Heap Implementation Details","topic":"Trees","definition":"Max-heap: parent ≥ children. Stored as array: parent at i, children at 2i+1 and 2i+2.","intuition":"Conceptually a tree, stored as array — parent-child relationships via index formulas.","formula":"Parent: ⌊(i-1)/2⌋. Left child: 2i+1. Right child: 2i+2. Heapify: O(log n).","difficulty":"medium","importance":8,"exam_trick":"Heapify is O(log n). Building heap bottom-up using n/2 heapify calls: O(n) total.","common_mistake":"Inserting n elements one-by-one into heap → O(n log n). Build-heap → O(n). HUGE difference.","pyq_insight":"GATE: trace heap insertion/deletion; prove build-heap is O(n); k-th smallest using heap.","relations":[{"to":"heaps","type":"part_of"}]},
]

DM_CONCEPTS = [
  {"id":"pigeonhole","name":"Pigeonhole Principle","topic":"Combinatorics","definition":"If n+1 objects placed in n holes, at least one hole has ≥2 objects.","intuition":"5 socks in 4 drawers — at least one drawer has 2 socks. Simple but powerful.","formula":"Generalized: if kn+1 objects in n holes → at least one hole has ≥k+1 objects.","difficulty":"medium","importance":7,"exam_trick":"Many GATE DM proofs use pigeonhole — know when to apply it.","common_mistake":"Pigeonhole proves EXISTENCE not CONSTRUCTION — doesn't tell you WHICH hole is full.","pyq_insight":"GATE: prove existence of some property using pigeonhole (birthday problem type).","relations":[]},
  {"id":"generating_functions","name":"Generating Functions","topic":"Combinatorics","definition":"Power series where coefficient of xⁿ encodes the nth term of a sequence.","intuition":"Package a whole sequence of numbers into one polynomial for algebraic manipulation.","formula":"Ordinary GF: G(x) = Σ aₙxⁿ. Solve recurrences by algebraic manipulation.","difficulty":"hard","importance":6,"exam_trick":"Convolution of GFs = multiplication. Used for counting collections of objects.","common_mistake":"Generating function is a formal power series — convergence doesn't matter for counting.","pyq_insight":"GATE: solve recurrence or count arrangements using generating function approach.","relations":[]},
  {"id":"boolean_lattice","name":"Lattices & Boolean Algebras","topic":"Algebraic Structures","definition":"Lattice: POSET where every pair has LUB (join) and GLB (meet). Boolean algebra: complemented distributive lattice.","intuition":"Lattice is a structured hierarchy. Boolean algebra is the mathematical foundation of digital logic.","formula":"Boolean algebra identifies: complement, join (+), meet (·). De Morgan's laws hold.","difficulty":"hard","importance":7,"exam_trick":"Power set of any set with ⊆ forms a Boolean algebra. Divisibility with LCM/GCD forms lattice.","common_mistake":"Not every POSET is a lattice (some pairs may lack LUB or GLB).","pyq_insight":"GATE: identify if given POSET is a lattice; find supremum/infimum of elements.","relations":[{"to":"relations","type":"depends_on"}]},
  {"id":"group_theory","name":"Groups, Rings & Fields","topic":"Algebraic Structures","definition":"Group: set with binary operation satisfying closure, associativity, identity, inverse.","intuition":"Group = most minimal structure with an invertible operation. Fields have two operations (like ℝ).","formula":"Abelian group: commutative. Ring: group + second op with distributivity. Field: ring with division.","difficulty":"hard","importance":6,"exam_trick":"Integers mod p (prime): (Zₚ, +, ×) forms a field — every nonzero element has multiplicative inverse.","common_mistake":"Every field is a ring, every ring is a group under addition — but not vice versa.","pyq_insight":"GATE: identify algebraic structure; verify group axioms; find order of element.","relations":[]},
  {"id":"eulerian_hamiltonian","name":"Eulerian & Hamiltonian Paths","topic":"Graph Theory","definition":"Eulerian: visits every edge exactly once. Hamiltonian: visits every vertex exactly once.","intuition":"Eulerian = drawing without lifting pen. Hamiltonian = visiting every city once.","formula":"Eulerian circuit: connected + all even degrees. Path: exactly 2 odd-degree vertices.","difficulty":"medium","importance":9,"exam_trick":"Eulerian is polynomial to decide. Hamiltonian is NP-complete. HUGE complexity difference.","common_mistake":"Eulerian circuit: ALL vertices must have even degree. Eulerian path: exactly 2 odd-degree vertices.","pyq_insight":"GATE: determine Eulerian/Hamiltonian property; count Eulerian circuits; design graph with property.","relations":[{"to":"graph_theory","type":"part_of"}]},
  {"id":"chromatic","name":"Graph Coloring & Chromatic Number","topic":"Graph Theory","definition":"Chromatic number χ(G): minimum colors needed so no adjacent vertices share a color.","intuition":"Color a map so no bordering regions share a color — classic graph coloring.","formula":"Bipartite: χ=2. Kₙ: χ=n. Cₙ: χ=2 (even), 3 (odd). Planar: χ≤4 (four-color theorem).","difficulty":"hard","importance":7,"exam_trick":"Graph is bipartite iff it has no odd cycles iff it is 2-colorable.","common_mistake":"Chromatic polynomial ≠ chromatic number. Polynomial counts valid colorings with k colors.","pyq_insight":"GATE: find chromatic number; check bipartiteness; apply 4-color theorem for planar graphs.","relations":[{"to":"graph_theory","type":"part_of"}]},
]

CD_CONCEPTS = [
  {"id":"sdts","name":"Syntax-Directed Translations (SDT)","topic":"Semantic Analysis","definition":"Grammar with semantic actions attached to productions. Computes attributes during parsing.","intuition":"Annotate parse tree with computed values — type checking, expression evaluation, code generation.","formula":"S-attributed SDD: only synthesized attributes (bottom-up). L-attributed: inherited too (LL friendly).","difficulty":"hard","importance":8,"exam_trick":"S-attributed SDDs are evaluated during LR parsing naturally. L-attributed needs care in LL.","common_mistake":"Inherited attributes depend on PARENT and SIBLINGS. Synthesized depend on CHILDREN.","pyq_insight":"GATE: evaluate attribute grammar on given parse tree; compute attribute values.","relations":[{"to":"parsing","type":"depends_on"}]},
  {"id":"ir_code","name":"Three-Address Code (TAC)","topic":"Code Generation","definition":"Intermediate representation where each instruction has at most 3 operands.","intuition":"Like assembly but with unlimited virtual registers — simple, linear form.","formula":"Forms: x=y op z, x=op y, x=y, goto L, if x goto L, call f,n.","difficulty":"medium","importance":7,"exam_trick":"TAC is used implicitly in all modern compilers (LLVM IR is essentially refined TAC).","common_mistake":"TAC uses temporary variables (t1, t2...). Each TAC instruction = at most ONE operation.","pyq_insight":"GATE: generate TAC for given expression; count temporaries.","relations":[]},
  {"id":"dag_ir","name":"DAG Representation","topic":"Code Generation","definition":"Directed Acyclic Graph for expression/basic block code — shares common subexpressions.","intuition":"Instead of computing x+y twice, compute once and reuse — DAG detects this automatically.","formula":"Build DAG: each new unique expression gets a node. Same expression → point to existing node.","difficulty":"hard","importance":7,"exam_trick":"DAG node count < expression tree nodes iff common subexpressions exist.","common_mistake":"DAG is for a SINGLE basic block. Across blocks, need global CSE with data flow analysis.","pyq_insight":"GATE: build DAG for expression; identify eliminated computations; count nodes.","relations":[{"to":"optimization","type":"part_of"}]},
  {"id":"activation_record","name":"Activation Records & Runtime Stack","topic":"Runtime Environment","definition":"Stack frame for each function call containing locals, parameters, return address, and saved registers.","intuition":"Function call = push a new booklet onto a stack. Return = rip it off and restore.","formula":"Frame: dynamic link (caller frame pointer), return address, parameters, locals, saved registers.","difficulty":"medium","importance":7,"exam_trick":"Static scoping uses static link (access link) to find non-local variables.","common_mistake":"Static vs dynamic scope: static = at definition. Dynamic = at call time. Most languages use static.","pyq_insight":"GATE: trace activation record stack for recursive function; identify frame contents.","relations":[]},
  {"id":"ll1_parsing","name":"LL(1) Parsing","topic":"Parsing","definition":"Top-down predictive parser using 1 lookahead token and FIRST/FOLLOW sets.","intuition":"Read one token ahead to decide which production to apply — no backtracking needed.","formula":"For grammar to be LL(1): no left recursion, left-factored, no FIRST-FOLLOW conflicts.","difficulty":"hard","importance":9,"exam_trick":"Left recursion: A→Aα | β. Eliminate: A→βA', A'→αA' | ε.","common_mistake":"LL(1) requires the grammar to be modified. LR(1) handles a wider class without modification.","pyq_insight":"GATE: check LL(1) condition; eliminate left recursion; build LL(1) table.","relations":[{"to":"first_follow","type":"depends_on"}]},
  {"id":"lalr1","name":"LALR(1) Parsing","topic":"Parsing","definition":"Look-Ahead LR parser — merges LR(1) states with identical LR(0) cores.","intuition":"LR(1) reduced to practical size by merging similar states — almost as powerful, much smaller.","formula":"LR(0) ⊂ SLR(1) ⊂ LALR(1) ⊂ LR(1). LALR(1) is yacc/bison's algorithm.","difficulty":"hard","importance":8,"exam_trick":"LALR(1) may have reduce-reduce conflicts that LR(1) would not. SLR uses FOLLOW (weaker).","common_mistake":"Merging LR(1) states to get LALR(1) can introduce conflicts — verify no R-R conflicts arise.","pyq_insight":"GATE: count LR(0)/LALR items; identify conflict type in parsing table.","relations":[{"to":"parsing","type":"part_of"}]},
]

LA_CONCEPTS = [
  {"id":"vector_spaces","name":"Vector Spaces & Subspaces","topic":"Linear Algebra","definition":"Set V with vector addition and scalar multiplication satisfying 8 axioms.","intuition":"Vectors can be added and scaled — the result stays 'in the same world'.","formula":"Subspace test: closed under addition and scalar multiplication; contains zero vector.","difficulty":"medium","importance":7,"exam_trick":"Column space, null space, row space of A are all vector subspaces.","common_mistake":"A single vector can span R^n iff it's in R^1. Span of {v} is just the line through v.","pyq_insight":"GATE: verify subspace property; find basis of null space or column space.","relations":[]},
  {"id":"linear_transform","name":"Linear Transformations","topic":"Linear Algebra","definition":"Function T: V→W preserving addition and scalar multiplication. T(au+bv)=aT(u)+bT(v).","intuition":"Matrix multiplication IS a linear transformation. Every matrix represents one.","formula":"Kernel = null space. Image = column space. rank(T) + nullity(T) = dim(V).","difficulty":"hard","importance":7,"exam_trick":"T is injective iff kernel = {0}. T is surjective iff image = W.","common_mistake":"Rank-nullity: nullity = n - rank(A), where n = NUMBER OF COLUMNS, not rows.","pyq_insight":"GATE: find kernel and image of T; verify rank-nullity theorem.","relations":[{"to":"rank_nullity","type":"depends_on"}]},
  {"id":"qr_decomp","name":"LU & QR Decomposition","topic":"Linear Algebra","definition":"LU: A = LU (lower × upper triangular). QR: A = QR (orthogonal × upper triangular).","intuition":"Factorize matrix to make solving systems cheaper — one factorization, many solves.","formula":"LU factorization: Gaussian elimination process. Solve Ax=b as Ly=b then Ux=y.","difficulty":"hard","importance":6,"exam_trick":"LU: O(n³) factorization, O(n²) per solve. QR: better for least squares.","common_mistake":"LU exists without pivoting only if all leading principal minors are nonzero.","pyq_insight":"GATE: less common. Know Gauss elimination reduces to LU factorization.","relations":[]},
  {"id":"quadratic_form","name":"Quadratic Forms & Definiteness","topic":"Linear Algebra","definition":"Quadratic form Q(x) = xᵀAx. Classified by eigenvalue signs: positive/negative/semi/indefinite.","intuition":"Like x²+y² (bowl shape) vs -x²-y² (inverted bowl) vs x²-y² (saddle).","formula":"Positive definite: all eigenvalues > 0. Negative definite: all < 0. Indefinite: mixed.","difficulty":"hard","importance":7,"exam_trick":"For 2×2: pos def iff det(A)>0 AND a₁₁>0. Test leads directly from eigenvalues.","common_mistake":"Semi-definite: some eigenvalues are ZERO. Neither not positive definite nor negative definite.","pyq_insight":"GATE: classify quadratic form; relate to max/min of function with Hessian matrix.","relations":[{"to":"eigenvalues","type":"depends_on"}]},
]

PS_CONCEPTS = [
  {"id":"markov_chain","name":"Markov Chains","topic":"Stochastic Processes","definition":"Sequence of states where next state depends ONLY on current state (memoryless).","intuition":"Each step only looks at where you are now — history is irrelevant.","formula":"P[Xₙ₊₁=j | Xₙ=i] = pᵢⱼ (transition probability). Stationary dist: πP = π.","difficulty":"hard","importance":7,"exam_trick":"To find stationary distribution: solve πP = π with Σπᵢ = 1.","common_mistake":"Ergodic Markov chain: irreducible + aperiodic → unique stationary distribution exists.","pyq_insight":"GATE: compute k-step transition probability; find stationary distribution.","relations":[]},
  {"id":"joint_dist","name":"Joint & Marginal Distributions","topic":"Statistics","definition":"Joint: P(X=x, Y=y). Marginal: sum/integrate joint over the other variable.","intuition":"Joint = full picture. Marginal = collapse one dimension (like projecting a 2D scatter).","formula":"Marginal: P(X=x) = ΣᵧP(X=x, Y=y). Covariance: E[XY] - E[X]E[Y].","difficulty":"medium","importance":8,"exam_trick":"X, Y independent iff joint PDF = f_X(x) × f_Y(y) — factorizes!","common_mistake":"Zero covariance does NOT imply independence (only for jointly Gaussian distributions).","pyq_insight":"GATE: compute marginal from joint; check independence; find P(X+Y<k).","relations":[{"to":"expectation_variance","type":"depends_on"}]},
  {"id":"bernoulli_geometric","name":"Bernoulli & Geometric Distribution","topic":"Probability","definition":"Bernoulli: single trial, P(success)=p. Geometric: number of trials until first success.","intuition":"Bernoulli = single coin flip. Geometric = how many flips until first head.","formula":"Bernoulli: E[X]=p, Var=p(1-p). Geometric: E[X]=1/p, Var=(1-p)/p².","difficulty":"medium","importance":7,"exam_trick":"Geometric is the ONLY discrete memoryless distribution. Exponential is the continuous version.","common_mistake":"Geometric P(X=k): (1-p)^(k-1) × p. First failure doesn't count — only the k-th trial is success.","pyq_insight":"GATE: use geometric distribution for waiting time; compute E[X] and P(X>k).","relations":[{"to":"distributions","type":"part_of"}]},
  {"id":"clt","name":"Central Limit Theorem (CLT)","topic":"Statistics","definition":"Sum of n IID random variables approaches Normal distribution as n→∞.","intuition":"No matter what distribution you sample from, average of many samples looks normal.","formula":"(X̄ - μ)/(σ/√n) → N(0,1) as n→∞. Works for n≥30 in practice.","difficulty":"medium","importance":7,"exam_trick":"CLT applies to SUMS and MEANS. Individual samples may still be non-normal.","common_mistake":"CLT doesn't say the distribution BECOMES normal — only that the SAMPLE MEAN approaches normal.","pyq_insight":"GATE: approximate binomial with normal using CLT for large n.","relations":[{"to":"distributions","type":"depends_on"}]},
]

GA_CONCEPTS = [
  {"id":"syllogism","name":"Syllogisms","topic":"Logical Reasoning","definition":"Deductive argument with two premises and a conclusion. Validity tested with Venn diagrams.","intuition":"Draw all valid Venn diagram arrangements for premises — conclusion valid if it holds in ALL.","formula":"Universal: 'All A are B'. Particular: 'Some A are B'. Negative: 'No A are B'.","difficulty":"medium","importance":8,"exam_trick":"'Some A are B' does NOT imply 'Some A are not B'. Only draw what's forced by premises.","common_mistake":"Complementary syllogism: if 'All A are B', then 'Some A are B' is also true (particular follows from universal).","pyq_insight":"GATE GA: 2-3 syllogism questions. Use Venn diagram method consistently.","relations":[]},
  {"id":"number_series","name":"Number Series & Patterns","topic":"Quantitative Aptitude","definition":"Identify rule governing a sequence; find the next term or missing term.","intuition":"Differences, ratios, squares, cubes, alternating patterns — look for the generation rule.","formula":"Common patterns: arithmetic (diff constant), geometric (ratio constant), squares, cubes, Fibonacci.","difficulty":"medium","importance":7,"exam_trick":"Check second differences if first differences aren't constant. May be quadratic sequence.","common_mistake":"Assuming only one pattern applies — sometimes two interleaved patterns exist.","pyq_insight":"GATE GA: always appears. 1-2 questions on sequence completion.","relations":[]},
  {"id":"percentage_profit","name":"Percentages, Profit & Loss","topic":"Arithmetic","definition":"Percent = per hundred. Profit = SP - CP. Profit% = (Profit/CP) × 100.","intuition":"Everything relates back to the base (Cost Price for profit, original for percentage change).","formula":"Successive discounts a% then b%: Net discount = a + b - ab/100.","difficulty":"easy","importance":8,"exam_trick":"Successive discounts: NEVER add — use formula. Same discount twice ≠ double the discount.","common_mistake":"Profit% is on CP. Discount% is on Marked Price (MP). Base is different!","pyq_insight":"GATE GA: 1-2 questions on profit/loss or percentage every year.","relations":[]},
  {"id":"sets_venn","name":"Set Theory & Venn Diagrams","topic":"Logic","definition":"A∪B, A∩B, A-B, A' are basic operations. Inclusion-exclusion: |A∪B| = |A|+|B|-|A∩B|.","intuition":"Venn diagrams are the visual calculator of set operations.","formula":"|A∪B∪C| = |A|+|B|+|C|-|A∩B|-|B∩C|-|A∩C|+|A∩B∩C|","difficulty":"medium","importance":8,"exam_trick":"Draw Venn diagram and fill from innermost (triple intersection) outward.","common_mistake":"Forgetting to SUBTRACT elements counted twice and ADD BACK those subtracted too many times.","pyq_insight":"GATE GA: 'In a class of 100, 60 like math, 50 like physics...' — classic inclusion-exclusion.","relations":[]},
]

CALC_CONCEPTS = [
  {"id":"partial_diff","name":"Partial Derivatives","topic":"Multivariable Calculus","definition":"Derivative of a function of multiple variables with respect to one variable, others held constant.","intuition":"Rate of change in one direction while standing still in all others.","formula":"∂f/∂x: treat y as constant and differentiate w.r.t. x.","difficulty":"medium","importance":8,"exam_trick":"Chain rule for partial: df = (∂f/∂x)dx + (∂f/∂y)dy.","common_mistake":"Mixed partials: ∂²f/∂x∂y = ∂²f/∂y∂x (if continuous). Order doesn't matter (Clairaut's theorem).","pyq_insight":"GATE EM: multivariable maxima/minima using partial derivatives.","relations":[{"to":"maxima_minima","type":"depends_on"}]},
  {"id":"double_integral","name":"Double & Triple Integrals","topic":"Multivariable Calculus","definition":"Integration over 2D or 3D regions. Order of integration can be reversed (Fubini's theorem).","intuition":"Volume under a surface = double integral of height function over base region.","formula":"∫∫f(x,y)dA. For polar: x=rcosθ, y=rsinθ, dA = r dr dθ.","difficulty":"hard","importance":8,"exam_trick":"Convert to polar when integrand has x²+y². Jacobian for polar = r.","common_mistake":"Limits of inner integral can depend on outer variable. Sketch the region first.","pyq_insight":"GATE EM: change order of integration; compute area using double integral.","relations":[]},
  {"id":"fourier_series","name":"Fourier Series","topic":"Series","definition":"Representing a periodic function as an infinite sum of sines and cosines.","intuition":"Every periodic signal = sum of pure tones at harmonically related frequencies.","formula":"f(x) = a₀/2 + Σ(aₙcos(nπx/L) + bₙsin(nπx/L))","difficulty":"hard","importance":7,"exam_trick":"Even function: bₙ=0 (only cosines). Odd function: aₙ=0 (only sines). Check this first!","common_mistake":"Fourier series converges to average of left/right limits at discontinuities (Gibbs phenomenon).","pyq_insight":"GATE EM: find Fourier coefficients; determine if function is odd/even.","relations":[]},
  {"id":"laplace","name":"Laplace Transform","topic":"Transforms","definition":"Transforms time-domain function f(t) to complex frequency domain F(s).","intuition":"Converts differential equations into algebraic equations — solve, then invert.","formula":"L{f(t)} = F(s) = ∫₀^∞ f(t)e^(-st)dt. L{eᵃᵗ} = 1/(s-a). L{sin(at)} = a/(s²+a²).","difficulty":"hard","importance":7,"exam_trick":"Initial value theorem: lim f(t) as t→0 = lim sF(s) as s→∞.","common_mistake":"Laplace requires f(t)=0 for t<0 (causal). Not for arbitrary functions.","pyq_insight":"GATE EM: find Laplace of given function; use for ODE solution.","relations":[]},
  {"id":"differential_equations","name":"Ordinary Differential Equations","topic":"Calculus","definition":"Equations relating a function with its derivatives. Classified by order and linearity.","intuition":"Model change — population growth, circuit response, spring motion.","formula":"1st order linear: dy/dx + P(x)y = Q(x). Integrating factor: μ=e^∫P(x)dx.","difficulty":"hard","importance":8,"exam_trick":"Homogeneous ODE (second order): characteristic equation. Roots real/complex/repeated → different solutions.","common_mistake":"Particular solution method: undetermined coefficients works only for polynomials/exp/trig RHS.","pyq_insight":"GATE EM: solve 1st or 2nd order ODE; identify type; apply integrating factor.","relations":[]},
]

def build_all():
    return {
        "dl": DL_CONCEPTS,
        "coa": COA_CONCEPTS,
        "pds": PDS_CONCEPTS,
        "dm": DM_CONCEPTS,
        "cd": CD_CONCEPTS,
        "la": LA_CONCEPTS,
        "ps": PS_CONCEPTS,
        "ga": GA_CONCEPTS,
        "calc": CALC_CONCEPTS,
    }

def merge_into_data_js(new_concepts: dict, data_js_path: Path):
    text = data_js_path.read_text(encoding="utf-8", errors="ignore")
    existing = {}
    m = re.search(r'const CONCEPTS=(\{[\s\S]*?\});\n', text)
    if m:
        try:
            existing = json.loads(m.group(1))
        except:
            existing = {}

    merged = dict(existing)
    added_total = 0
    for sid, concepts in new_concepts.items():
        if sid not in merged:
            merged[sid] = []
        existing_ids = {c['id'] for c in merged[sid]}
        new = [c for c in concepts if c['id'] not in existing_ids]
        merged[sid].extend(new)
        added_total += len(new)

    payload = json.dumps(merged, ensure_ascii=False, indent=2)
    new_block = f"\n// ═══ CONCEPTS DATA ═══\nconst CONCEPTS={payload};\n"
    updated = re.sub(r'\n// ═══ CONCEPTS DATA ═══\nconst CONCEPTS=\{[\s\S]*?\};\n', new_block, text)
    if updated == text:
        marker = "// ═══ REVISION CONTENT DATA ═══"
        updated = text.replace(marker, new_block + "\n" + marker)
    data_js_path.write_text(updated, encoding="utf-8")

    total = sum(len(v) for v in merged.values())
    print(f"\n✅ Concept Engine v3 Merge Complete!")
    print(f"   New concepts added: {added_total}")
    print(f"   Total concepts now: {total}")
    for sid in sorted(merged):
        print(f"   {sid:6s}: {len(merged[sid])} concepts")

if __name__ == "__main__":
    data_js = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DATA_JS
    merge_into_data_js(build_all(), data_js)
